import React, { useMemo, useState } from 'react';

const scenario = {
  eyebrow: 'Commercial extension', title: 'Continuous Control Testing Lab',
  summary: 'Model audit capacity gains and stage ERP evidence collection, control testing, remediation, and auditor delivery.',
  volumeLabel: 'Annual control tests', unitValueLabel: 'Average test cost', issueRateLabel: 'Exception / rework rate', improvementLabel: 'Automatable share',
  defaults: [4200, 680, 18, 62], baselineLabel: 'Annual testing cost', opportunityLabel: 'Exception and rework cost', resultLabel: 'Expected controlled savings',
  pricing: 'Annual subscription by entity and control count, with audit-firm portfolio and evidence-volume tiers.',
  milestones: ['Connect one ERP control population', 'Automate evidence sufficiency and sampling checks', 'Route exceptions through maker-checker remediation', 'Release auditor-ready PBC and workpaper exports'],
  connectors: ['ERP and identity evidence', 'Workiva / AuditBoard workpapers', 'Ticketing and remediation status'],
};

const usd = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number(value || 0));

export default function CodexCustomVizFeature() {
  const [volume, setVolume] = useState(scenario.defaults[0]); const [unitValue, setUnitValue] = useState(scenario.defaults[1]);
  const [issueRate, setIssueRate] = useState(scenario.defaults[2]); const [improvement, setImprovement] = useState(scenario.defaults[3]);
  const result = useMemo(() => { const baseline=Number(volume)*Number(unitValue); const opportunity=baseline*Number(issueRate)/100; return { baseline, opportunity, captured:opportunity*Number(improvement)/100 }; }, [volume, unitValue, issueRate, improvement]);
  const field = (label,value,setter,suffix='') => <label style={{display:'grid',gap:7,fontWeight:750,color:'#475569'}}><span>{label}</span><div style={{display:'flex',alignItems:'center',gap:8}}><input type="number" min="0" step="any" value={value} onChange={event=>setter(event.target.value)} style={{width:'100%',padding:'11px 12px',border:'1px solid #cbd5e1',borderRadius:9}}/>{suffix&&<b style={{color:'#0f766e'}}>{suffix}</b>}</div></label>;
  const metric = (label,value) => <article style={{background:'#fff',border:'1px solid #dbe3ec',borderRadius:14,padding:18}}><span style={{fontSize:12,color:'#64748b',fontWeight:750}}>{label}</span><strong style={{display:'block',fontSize:27,marginTop:7}}>{usd(value)}</strong></article>;
  return <section style={{padding:24,color:'#172033'}}><p style={{margin:0,color:'#0f766e',fontSize:12,fontWeight:850,textTransform:'uppercase',letterSpacing:'.12em'}}>{scenario.eyebrow}</p><h1 style={{fontSize:32,margin:'7px 0'}}>{scenario.title}</h1><p style={{color:'#64748b',maxWidth:850}}>{scenario.summary}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:13,margin:'20px 0'}}>{metric(scenario.baselineLabel,result.baseline)}{metric(scenario.opportunityLabel,result.opportunity)}{metric(scenario.resultLabel,result.captured)}{metric('Monthly realized value',result.captured/12)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16}}><article style={{background:'#fff',border:'1px solid #dbe3ec',borderRadius:14,padding:20}}><h2 style={{marginTop:0}}>Interactive pilot assumptions</h2><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14}}>{field(scenario.volumeLabel,volume,setVolume)}{field(scenario.unitValueLabel,unitValue,setUnitValue)}{field(scenario.issueRateLabel,issueRate,setIssueRate,'%')}{field(scenario.improvementLabel,improvement,setImprovement,'%')}</div><div style={{marginTop:17,padding:14,borderRadius:10,background:'#f0fdfa',color:'#134e4a'}}><strong>Commercial model</strong><p style={{marginBottom:0}}>{scenario.pricing}</p></div></article><article style={{background:'#fff',border:'1px solid #dbe3ec',borderRadius:14,padding:20}}><h2 style={{marginTop:0}}>Measured rollout</h2>{scenario.milestones.map((item,index)=><div key={item} style={{display:'grid',gridTemplateColumns:'32px 1fr',gap:10,alignItems:'center',padding:'10px 0',borderBottom:'1px solid #e2e8f0'}}><span style={{display:'grid',placeItems:'center',width:28,height:28,borderRadius:'50%',background:'#0f766e',color:'#fff',fontWeight:850}}>{index+1}</span><strong>{item}</strong></div>)}</article></div><article style={{background:'#fff',border:'1px solid #dbe3ec',borderRadius:14,padding:20,marginTop:16}}><h2 style={{marginTop:0}}>Authoritative connector plan</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{scenario.connectors.map((item,index)=><div key={item} style={{padding:15,border:'1px solid #dbe3ec',borderRadius:11,background:'#f8fafc'}}><span style={{fontSize:11,fontWeight:850,color:index?'#b45309':'#047857'}}>{index?'PLANNED':'PILOT'}</span><h3 style={{fontSize:15}}>{item}</h3><p style={{fontSize:12,color:'#64748b'}}>Require stable IDs, versioned schemas, idempotent receipts, explicit failures, and reconciliation evidence.</p></div>)}</div></article></section>;
}
