import { Shield, AlertTriangle, Search, ClipboardList, FileCheck, FileText, Users, Monitor, DollarSign, UserCheck, KeyRound, GitBranch, BookOpen, ScrollText, Target, Calendar, Scale, Bell } from 'lucide-react'
import { api } from '../services/api'

export const featureConfigs = {
  controls: {
    title: 'Control Testing',
    resource: 'controls',
    icon: Shield,
    idField: 'control_id',
    aiField: 'ai_analysis',
    aiAction: (id) => api.analyzeControl(id),
    aiLabel: 'AI Analyze Control',
    columns: [
      { key: 'control_id', label: 'Control ID' },
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'owner', label: 'Owner' },
      { key: 'frequency', label: 'Frequency' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'effectiveness', label: 'Effectiveness', badge: true },
    ],
    formFields: [
      { name: 'control_id', label: 'Control ID', required: true },
      { name: 'name', label: 'Name', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'category', label: 'Category', type: 'select', options: ['Financial Reporting', 'Operations', 'Compliance', 'IT', 'Entity Level'] },
      { name: 'owner', label: 'Owner' },
      { name: 'frequency', label: 'Frequency', type: 'select', options: ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Annually'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Pending', 'In Progress', 'Completed', 'Not Applicable'], badge: true },
      { name: 'effectiveness', label: 'Effectiveness', type: 'select', options: ['Not Tested', 'Effective', 'Partially Effective', 'Ineffective'], badge: true },
      { name: 'last_tested', label: 'Last Tested', type: 'date' },
    ],
  },

  'risk-assessments': {
    title: 'Risk Assessment',
    resource: 'risk-assessments',
    icon: AlertTriangle,
    idField: 'risk_id',
    aiField: 'ai_analysis',
    aiAction: (id) => api.analyzeRisk(id),
    aiLabel: 'AI Analyze Risk',
    columns: [
      { key: 'risk_id', label: 'Risk ID' },
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'likelihood', label: 'Likelihood', badge: true },
      { key: 'impact', label: 'Impact', badge: true },
      { key: 'risk_score', label: 'Score' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'risk_id', label: 'Risk ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'category', label: 'Category', type: 'select', options: ['Financial', 'Operational', 'Compliance', 'Strategic', 'Technology', 'Reputational'] },
      { name: 'likelihood', label: 'Likelihood', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { name: 'impact', label: 'Impact', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { name: 'risk_score', label: 'Risk Score (1-10)', type: 'number' },
      { name: 'mitigation', label: 'Mitigation Strategy', type: 'textarea' },
      { name: 'owner', label: 'Owner' },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Mitigated', 'Closed'], badge: true },
    ],
  },

  evidence: {
    title: 'Evidence Collection',
    resource: 'evidence',
    icon: Search,
    idField: 'evidence_id',
    aiAction: (id) => api.analyzeEvidence(id),
    aiLabel: 'AI Assess Sufficiency',
    columns: [
      { key: 'evidence_id', label: 'Evidence ID' },
      { key: 'title', label: 'Title' },
      { key: 'control_ref', label: 'Control Ref' },
      { key: 'type', label: 'Type' },
      { key: 'collected_by', label: 'Collected By' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'evidence_id', label: 'Evidence ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'control_ref', label: 'Control Reference' },
      { name: 'type', label: 'Type', type: 'select', options: ['Document', 'Screenshot', 'Report', 'Email', 'System Extract', 'Interview Notes', 'Observation'] },
      { name: 'source', label: 'Source' },
      { name: 'collected_by', label: 'Collected By' },
      { name: 'collected_date', label: 'Collected Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['Pending Review', 'Approved', 'Rejected', 'Archived'], badge: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  compliance: {
    title: 'Compliance Checklist',
    resource: 'compliance',
    icon: ClipboardList,
    idField: 'item_id',
    aiAction: (id) => api.analyzeCompliance(id),
    aiLabel: 'AI Gap Assessment',
    columns: [
      { key: 'item_id', label: 'Item ID' },
      { key: 'section', label: 'Section' },
      { key: 'requirement', label: 'Requirement' },
      { key: 'assignee', label: 'Assignee' },
      { key: 'due_date', label: 'Due Date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'item_id', label: 'Item ID', required: true },
      { name: 'section', label: 'SOX Section', type: 'select', options: ['Section 302', 'Section 404', 'Section 906', 'Section 802', 'Section 301', 'Section 806', 'Section 1001'] },
      { name: 'requirement', label: 'Requirement', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'assignee', label: 'Assignee' },
      { name: 'due_date', label: 'Due Date', type: 'date' },
      { name: 'completion_date', label: 'Completion Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['Not Started', 'In Progress', 'Completed', 'Not Applicable'], badge: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  deficiencies: {
    title: 'Deficiency Tracking',
    resource: 'deficiencies',
    icon: FileCheck,
    idField: 'deficiency_id',
    aiField: 'ai_analysis',
    aiAction: (id) => api.analyzeDeficiency(id),
    aiLabel: 'AI Classify Deficiency',
    columns: [
      { key: 'deficiency_id', label: 'Deficiency ID' },
      { key: 'title', label: 'Title' },
      { key: 'control_ref', label: 'Control Ref' },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'classification', label: 'Classification' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'deficiency_id', label: 'Deficiency ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'control_ref', label: 'Control Reference' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'], badge: true },
      { name: 'classification', label: 'Classification', type: 'select', options: ['Control Deficiency', 'Significant Deficiency', 'Material Weakness'] },
      { name: 'identified_date', label: 'Identified Date', type: 'date' },
      { name: 'remediation_plan', label: 'Remediation Plan', type: 'textarea' },
      { name: 'owner', label: 'Owner' },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Remediated', 'Closed'], badge: true },
    ],
  },

  walkthroughs: {
    title: 'Walkthrough Documentation',
    resource: 'walkthroughs',
    icon: FileText,
    idField: 'walkthrough_id',
    aiField: 'ai_narrative',
    aiAction: (id) => api.generateNarrative(id),
    aiLabel: 'AI Generate Narrative',
    columns: [
      { key: 'walkthrough_id', label: 'ID' },
      { key: 'process_name', label: 'Process' },
      { key: 'department', label: 'Department' },
      { key: 'performed_by', label: 'Performed By' },
      { key: 'performed_date', label: 'Date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'walkthrough_id', label: 'Walkthrough ID', required: true },
      { name: 'process_name', label: 'Process Name', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'department', label: 'Department', type: 'select', options: ['Finance', 'Accounting', 'IT', 'HR', 'Operations', 'Procurement', 'Sales', 'Legal'] },
      { name: 'performed_by', label: 'Performed By' },
      { name: 'performed_date', label: 'Performed Date', type: 'date' },
      { name: 'participants', label: 'Participants', type: 'textarea' },
      { name: 'findings', label: 'Findings', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'select', options: ['Draft', 'In Progress', 'Completed', 'Approved'], badge: true },
    ],
  },

  'management-reviews': {
    title: 'Management Review',
    resource: 'management-reviews',
    icon: Users,
    idField: 'review_id',
    aiAction: (id) => api.analyzeReview(id),
    aiLabel: 'AI Review Assessment',
    columns: [
      { key: 'review_id', label: 'Review ID' },
      { key: 'title', label: 'Title' },
      { key: 'review_type', label: 'Type' },
      { key: 'reviewer', label: 'Reviewer' },
      { key: 'review_date', label: 'Date' },
      { key: 'conclusion', label: 'Conclusion', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'review_id', label: 'Review ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'review_type', label: 'Review Type', type: 'select', options: ['Account Reconciliation', 'Journal Entry Review', 'Budget vs Actual', 'Variance Analysis', 'Disclosure Review', 'Estimate Review'] },
      { name: 'reviewer', label: 'Reviewer' },
      { name: 'review_date', label: 'Review Date', type: 'date' },
      { name: 'period', label: 'Period' },
      { name: 'findings', label: 'Findings', type: 'textarea' },
      { name: 'conclusion', label: 'Conclusion', type: 'select', options: ['Satisfactory', 'Needs Improvement', 'Unsatisfactory'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Scheduled', 'In Progress', 'Completed', 'Deferred'], badge: true },
    ],
  },

  itgc: {
    title: 'IT General Controls',
    resource: 'itgc',
    icon: Monitor,
    idField: 'itgc_id',
    aiField: 'ai_analysis',
    aiAction: (id) => api.analyzeItgc(id),
    aiLabel: 'AI Analyze ITGC',
    columns: [
      { key: 'itgc_id', label: 'ITGC ID' },
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'system_name', label: 'System' },
      { key: 'control_type', label: 'Type' },
      { key: 'test_result', label: 'Test Result', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'itgc_id', label: 'ITGC ID', required: true },
      { name: 'name', label: 'Name', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'category', label: 'Category', type: 'select', options: ['Access Security', 'Change Management', 'Computer Operations', 'Program Development', 'Data Backup'] },
      { name: 'system_name', label: 'System Name' },
      { name: 'control_type', label: 'Control Type', type: 'select', options: ['Preventive', 'Detective', 'Corrective'] },
      { name: 'owner', label: 'Owner' },
      { name: 'test_result', label: 'Test Result', type: 'select', options: ['Not Tested', 'Pass', 'Fail', 'Partially Effective'], badge: true },
      { name: 'test_date', label: 'Test Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Under Review'], badge: true },
    ],
  },

  'financial-reviews': {
    title: 'Financial Statement Review',
    resource: 'financial-reviews',
    icon: DollarSign,
    idField: 'review_id',
    aiField: 'ai_analysis',
    aiAction: (id) => api.analyzeFinancial(id),
    aiLabel: 'AI Analyze Financials',
    columns: [
      { key: 'review_id', label: 'Review ID' },
      { key: 'account_name', label: 'Account' },
      { key: 'period', label: 'Period' },
      { key: 'balance', label: 'Balance', render: (v) => `$${Number(v).toLocaleString()}` },
      { key: 'variance_pct', label: 'Variance %', render: (v) => `${v}%` },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'review_id', label: 'Review ID', required: true },
      { name: 'account_name', label: 'Account Name', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'period', label: 'Period' },
      { name: 'balance', label: 'Current Balance', type: 'number' },
      { name: 'prior_balance', label: 'Prior Balance', type: 'number' },
      { name: 'variance_pct', label: 'Variance %', type: 'number' },
      { name: 'reviewer', label: 'Reviewer' },
      { name: 'status', label: 'Status', type: 'select', options: ['Pending', 'In Progress', 'Completed', 'Requires Adjustment'], badge: true },
    ],
  },

  'sod-reviews': {
    title: 'Segregation of Duties',
    resource: 'sod-reviews',
    icon: UserCheck,
    idField: 'sod_id',
    aiField: 'ai_analysis',
    aiAction: (id) => api.analyzeSod(id),
    aiLabel: 'AI Analyze SoD Conflict',
    columns: [
      { key: 'sod_id', label: 'SoD ID' },
      { key: 'user_name', label: 'User' },
      { key: 'role_1', label: 'Role 1' },
      { key: 'role_2', label: 'Role 2' },
      { key: 'system_name', label: 'System' },
      { key: 'risk_level', label: 'Risk Level', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'sod_id', label: 'SoD ID', required: true },
      { name: 'user_name', label: 'User Name', required: true },
      { name: 'role_1', label: 'Role 1' },
      { name: 'role_2', label: 'Role 2' },
      { name: 'system_name', label: 'System' },
      { name: 'conflict_type', label: 'Conflict Type', type: 'select', options: ['Authorization', 'Custody', 'Record-keeping', 'Reconciliation'] },
      { name: 'risk_level', label: 'Risk Level', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'], badge: true },
      { name: 'mitigation', label: 'Mitigation', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'Mitigated', 'Accepted', 'Closed'], badge: true },
    ],
  },

  'access-reviews': {
    title: 'Access Control Review',
    resource: 'access-reviews',
    icon: KeyRound,
    idField: 'review_id',
    aiAction: (id) => api.analyzeAccess(id),
    aiLabel: 'AI Access Risk Analysis',
    columns: [
      { key: 'review_id', label: 'Review ID' },
      { key: 'user_name', label: 'User' },
      { key: 'system_name', label: 'System' },
      { key: 'access_level', label: 'Access Level' },
      { key: 'department', label: 'Department' },
      { key: 'appropriate', label: 'Appropriate', badge: true },
    ],
    formFields: [
      { name: 'review_id', label: 'Review ID', required: true },
      { name: 'user_name', label: 'User Name', required: true },
      { name: 'system_name', label: 'System' },
      { name: 'access_level', label: 'Access Level', type: 'select', options: ['Read Only', 'Read/Write', 'Admin', 'Super Admin', 'Service Account'] },
      { name: 'department', label: 'Department' },
      { name: 'last_login', label: 'Last Login', type: 'date' },
      { name: 'appropriate', label: 'Appropriate', type: 'select', options: ['Pending Review', 'Approved', 'Rejected', 'Needs Modification'], badge: true },
      { name: 'reviewer', label: 'Reviewer' },
      { name: 'review_date', label: 'Review Date', type: 'date' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  'change-requests': {
    title: 'Change Management',
    resource: 'change-requests',
    icon: GitBranch,
    idField: 'change_id',
    aiAction: (id) => api.analyzeChange(id),
    aiLabel: 'AI Change Risk Assessment',
    columns: [
      { key: 'change_id', label: 'Change ID' },
      { key: 'title', label: 'Title' },
      { key: 'system_name', label: 'System' },
      { key: 'change_type', label: 'Type' },
      { key: 'requestor', label: 'Requestor' },
      { key: 'risk_level', label: 'Risk', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'change_id', label: 'Change ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'system_name', label: 'System' },
      { name: 'change_type', label: 'Change Type', type: 'select', options: ['Emergency', 'Standard', 'Normal', 'Major'] },
      { name: 'requestor', label: 'Requestor' },
      { name: 'approver', label: 'Approver' },
      { name: 'request_date', label: 'Request Date', type: 'date' },
      { name: 'implementation_date', label: 'Implementation Date', type: 'date' },
      { name: 'risk_level', label: 'Risk Level', type: 'select', options: ['Low', 'Medium', 'High'], badge: true },
      { name: 'status', label: 'Status', type: 'select', options: ['Pending', 'Approved', 'Rejected', 'Implemented', 'Rolled Back'], badge: true },
    ],
  },

  'audit-reports': {
    title: 'Audit Reports',
    resource: 'audit-reports',
    icon: BookOpen,
    idField: 'report_id',
    aiField: 'ai_summary',
    aiAction: (id) => api.generateReport(id),
    aiLabel: 'AI Generate Summary',
    columns: [
      { key: 'report_id', label: 'Report ID' },
      { key: 'title', label: 'Title' },
      { key: 'audit_type', label: 'Type' },
      { key: 'period', label: 'Period' },
      { key: 'lead_auditor', label: 'Lead Auditor' },
      { key: 'findings_count', label: 'Findings' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'report_id', label: 'Report ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'audit_type', label: 'Audit Type', type: 'select', options: ['Internal Audit', 'External Audit', 'SOX 404', 'ITGC Review', 'Special Review'] },
      { name: 'scope', label: 'Scope', type: 'textarea' },
      { name: 'period', label: 'Period' },
      { name: 'lead_auditor', label: 'Lead Auditor' },
      { name: 'findings_count', label: 'Findings Count', type: 'number' },
      { name: 'opinion', label: 'Opinion', type: 'select', options: ['Unqualified', 'Qualified', 'Adverse', 'Disclaimer'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Draft', 'In Progress', 'Review', 'Final', 'Issued'], badge: true },
    ],
  },

  policies: {
    title: 'Policy Management',
    resource: 'policies',
    icon: ScrollText,
    idField: 'policy_id',
    aiField: 'ai_gap_analysis',
    aiAction: (id) => api.analyzePolicy(id),
    aiLabel: 'AI Gap Analysis',
    columns: [
      { key: 'policy_id', label: 'Policy ID' },
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'version', label: 'Version' },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'policy_id', label: 'Policy ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'category', label: 'Category', type: 'select', options: ['IT Security', 'Financial Reporting', 'HR', 'Compliance', 'Operations', 'Data Privacy', 'Risk Management'] },
      { name: 'version', label: 'Version' },
      { name: 'effective_date', label: 'Effective Date', type: 'date' },
      { name: 'review_date', label: 'Review Date', type: 'date' },
      { name: 'owner', label: 'Owner' },
      { name: 'status', label: 'Status', type: 'select', options: ['Draft', 'Active', 'Under Review', 'Retired'], badge: true },
    ],
  },

  remediations: {
    title: 'Remediation Tracking',
    resource: 'remediations',
    icon: Target,
    idField: 'remediation_id',
    aiAction: (id) => api.analyzeRemediation(id),
    aiLabel: 'AI Plan Assessment',
    columns: [
      { key: 'remediation_id', label: 'ID' },
      { key: 'title', label: 'Title' },
      { key: 'deficiency_ref', label: 'Deficiency Ref' },
      { key: 'owner', label: 'Owner' },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'due_date', label: 'Due Date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'remediation_id', label: 'Remediation ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'deficiency_ref', label: 'Deficiency Reference' },
      { name: 'action_plan', label: 'Action Plan', type: 'textarea' },
      { name: 'owner', label: 'Owner' },
      { name: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'], badge: true },
      { name: 'due_date', label: 'Due Date', type: 'date' },
      { name: 'completion_date', label: 'Completion Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['Not Started', 'In Progress', 'Completed', 'Overdue', 'Verified'], badge: true },
      { name: 'verification', label: 'Verification Notes', type: 'textarea' },
    ],
  },

  'audit-plans': {
    title: 'Audit Planning',
    resource: 'audit-plans',
    icon: Calendar,
    idField: 'plan_id',
    aiField: 'ai_suggestions',
    aiAction: (id) => api.suggestPlan(id),
    aiLabel: 'AI Suggest Improvements',
    columns: [
      { key: 'plan_id', label: 'Plan ID' },
      { key: 'title', label: 'Title' },
      { key: 'audit_type', label: 'Type' },
      { key: 'start_date', label: 'Start' },
      { key: 'end_date', label: 'End' },
      { key: 'lead_auditor', label: 'Lead' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'plan_id', label: 'Plan ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'audit_type', label: 'Audit Type', type: 'select', options: ['Annual SOX', 'Quarterly Review', 'ITGC Audit', 'Process Audit', 'Special Investigation'] },
      { name: 'start_date', label: 'Start Date', type: 'date' },
      { name: 'end_date', label: 'End Date', type: 'date' },
      { name: 'lead_auditor', label: 'Lead Auditor' },
      { name: 'team_members', label: 'Team Members', type: 'textarea' },
      { name: 'budget', label: 'Budget', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['Planning', 'Executing', 'Reporting', 'Completed', 'On Hold'], badge: true },
    ],
  },

  materiality: {
    title: 'Materiality Assessment',
    resource: 'materiality',
    icon: Scale,
    idField: 'assessment_id',
    aiField: 'ai_analysis',
    aiAction: (id) => api.analyzeMateriality(id),
    aiLabel: 'AI Analyze Materiality',
    columns: [
      { key: 'assessment_id', label: 'ID' },
      { key: 'title', label: 'Title' },
      { key: 'benchmark', label: 'Benchmark' },
      { key: 'materiality_threshold', label: 'Threshold', render: (v) => `$${Number(v).toLocaleString()}` },
      { key: 'period', label: 'Period' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'assessment_id', label: 'Assessment ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'benchmark', label: 'Benchmark', type: 'select', options: ['Total Revenue', 'Total Assets', 'Net Income', 'Equity', 'Gross Profit'] },
      { name: 'benchmark_value', label: 'Benchmark Value', type: 'number' },
      { name: 'materiality_threshold', label: 'Materiality Threshold', type: 'number' },
      { name: 'tolerable_misstatement', label: 'Tolerable Misstatement', type: 'number' },
      { name: 'period', label: 'Period' },
      { name: 'assessor', label: 'Assessor' },
      { name: 'status', label: 'Status', type: 'select', options: ['Draft', 'Approved', 'Revised'], badge: true },
    ],
  },

  incidents: {
    title: 'Incident Management',
    resource: 'incidents',
    icon: Bell,
    idField: 'incident_id',
    aiField: 'ai_analysis',
    aiAction: (id) => api.analyzeIncident(id),
    aiLabel: 'AI Analyze Incident',
    columns: [
      { key: 'incident_id', label: 'Incident ID' },
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'reported_by', label: 'Reported By' },
      { key: 'reported_date', label: 'Date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    formFields: [
      { name: 'incident_id', label: 'Incident ID', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'category', label: 'Category', type: 'select', options: ['Security Breach', 'Data Loss', 'System Outage', 'Compliance Violation', 'Fraud', 'Unauthorized Access', 'Process Failure'] },
      { name: 'severity', label: 'Severity', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'], badge: true },
      { name: 'reported_by', label: 'Reported By' },
      { name: 'reported_date', label: 'Reported Date', type: 'date' },
      { name: 'resolved_date', label: 'Resolved Date', type: 'date' },
      { name: 'root_cause', label: 'Root Cause', type: 'textarea' },
      { name: 'impact_assessment', label: 'Impact Assessment', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'select', options: ['Open', 'Investigating', 'Resolved', 'Closed'], badge: true },
    ],
  },
}
