module.exports = {
  caseType:'reviewed_sox_evidence_assessment',
  initialState:'control_registered',
  states:['control_registered','sources_reconciled','period_locked','test_calculated','independent_review','management_approved','effective','exception_open','remediated','corrected','reversed','closed'],
  createRoles:['control_owner','audit_manager'],
  assessmentRoles:['tester','independent_reviewer','audit_manager'],
  auditRoles:['audit_manager','independent_reviewer','external_auditor'],
  connectorRoles:['integration_operator','audit_manager'],
  evidenceKinds:['control_definition','ledger_snapshot','bank_billing_reconciliation','population_manifest','sample_manifest','calculation_workpaper','effective_date_record','late_data_record','boundary_case_result','golden_backtest_report','evidence_sufficiency_report','independent_review','management_signoff','exception_record','remediation_record','correction_record','reversal_record'],
  requiredSignals:['controlVersion','ledgerVersion','populationVersion','calculationVersion','policyVersion','safetyLimitsVerified','reconciliationStatus','evidenceSufficiency','goldenBacktestAccuracy','lateDataStatus','boundaryStatus','explainabilityStatus','periodLockStatus'],
  professionalBoundary:'Deterministic results are audit workpapers, not accounting entries, audit opinions, or regulatory conclusions. Segregated qualified financial and audit reviewers approve all conclusions.',
  connectors:[
    {name:'general_ledger',purpose:'read-only reconciled ledger snapshots'},
    {name:'bank_billing',purpose:'authoritative reconciliation receipts'},
    {name:'grc_audit',purpose:'control, finding, and sign-off versions'},
    {name:'identity',purpose:'segregation-of-duties membership receipts'},
    {name:'evidence_vault',purpose:'immutable encrypted workpaper pointers'},
    {name:'filing',purpose:'quarantined filing/export receipts'},
    {name:'notification',purpose:'deadline and exception receipts'},
  ],
  transitions:[
    {from:'control_registered',action:'reconcile_sources',to:'sources_reconciled',roles:['tester','integration_operator'],requiresEvidence:true},
    {from:'sources_reconciled',action:'lock_period',to:'period_locked',roles:['control_owner','audit_manager'],requiresEvidence:true,dualControl:true},
    {from:'period_locked',action:'record_test',to:'test_calculated',roles:['tester'],requiresEvidence:true},
    {from:'test_calculated',action:'submit_independent_review',to:'independent_review',roles:['independent_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'independent_review',action:'approve_management_conclusion',to:'management_approved',roles:['audit_manager','control_owner'],requiresEvidence:true,dualControl:true},
    {from:'management_approved',action:'record_effective',to:'effective',roles:['audit_manager'],requiresEvidence:true,dualControl:true},
    {from:'management_approved',action:'open_exception',to:'exception_open',roles:['independent_reviewer','audit_manager'],requiresEvidence:true},
    {from:'exception_open',action:'record_remediation',to:'remediated',roles:['control_owner'],requiresEvidence:true},
    {from:'remediated',action:'record_correction',to:'corrected',roles:['tester','independent_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'effective',action:'record_reversal',to:'reversed',roles:['audit_manager','independent_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'corrected',action:'close_assessment',to:'closed',roles:['audit_manager'],requiresEvidence:true},
    {from:'reversed',action:'close_assessment',to:'closed',roles:['audit_manager'],requiresEvidence:true},
  ],
  acceptedFixture:{controlVersion:'c1',ledgerVersion:'l1',populationVersion:'pop1',calculationVersion:'calc1',policyVersion:'p1',safetyLimitsVerified:true,reconciliationStatus:'balanced',evidenceSufficiency:0.99,goldenBacktestAccuracy:0.995,lateDataStatus:'included',boundaryStatus:'passed',explainabilityStatus:'complete',periodLockStatus:'locked'},
  rejectedFixture:{controlVersion:'c1',ledgerVersion:'l1',populationVersion:'pop1',calculationVersion:'calc1',policyVersion:'p1',safetyLimitsVerified:true,reconciliationStatus:'unbalanced',evidenceSufficiency:0.99,goldenBacktestAccuracy:0.995,lateDataStatus:'included',boundaryStatus:'passed',explainabilityStatus:'complete',periodLockStatus:'locked'},
  readyDisposition:'independent_financial_review_required',
  holdDisposition:'reconciliation_evidence_or_backtest_hold',
  decisionField:'auditConclusion',
  assess:(x)=>{const sufficiency=Number(x.evidenceSufficiency),accuracy=Number(x.goldenBacktestAccuracy);const ready=x.safetyLimitsVerified===true&&x.reconciliationStatus==='balanced'&&sufficiency>=0.98&&accuracy>=0.99&&x.lateDataStatus==='included'&&x.boundaryStatus==='passed'&&x.explainabilityStatus==='complete'&&x.periodLockStatus==='locked';return{disposition:ready?'independent_financial_review_required':'reconciliation_evidence_or_backtest_hold',auditConclusion:null,metrics:{evidenceSufficiency:sufficiency,goldenBacktestAccuracy:accuracy},versions:{control:x.controlVersion,ledger:x.ledgerVersion,population:x.populationVersion,calculation:x.calculationVersion}};},
};
