const pool = require('./config/db');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

async function seed() {
  console.log('Seeding database...');

  // Run schema
  const schema = fs.readFileSync(path.join(__dirname, 'config/schema.sql'), 'utf8');
  await pool.query(schema);

  // Seed user
  const hashedPassword = await bcrypt.hash(process.env.DEFAULT_PASSWORD || 'admin123', 10);
  await pool.query(
    `INSERT INTO users (email, password, name, role) VALUES ($1, $2, $3, $4) ON CONFLICT (email) DO UPDATE SET password = $2`,
    [process.env.DEFAULT_EMAIL || 'admin@soxaudit.com', hashedPassword, 'Admin User', 'admin']
  );

  // Helper to insert rows
  async function insertRows(table, rows) {
    for (const row of rows) {
      const keys = Object.keys(row);
      const values = Object.values(row);
      const placeholders = keys.map((_, i) => `$${i + 1}`).join(', ');
      try {
        await pool.query(`INSERT INTO ${table} (${keys.join(', ')}) VALUES (${placeholders}) ON CONFLICT DO NOTHING`, values);
      } catch (err) {
        // skip duplicate
      }
    }
  }

  // 1. Controls (15 items)
  await insertRows('controls', [
    { control_id: 'CTL-001', name: 'Revenue Recognition Review', description: 'Monthly review of revenue recognition entries per ASC 606', category: 'Financial Reporting', owner: 'Jane Smith', frequency: 'Monthly', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-03-15' },
    { control_id: 'CTL-002', name: 'Journal Entry Approval', description: 'All journal entries over $10K require manager approval', category: 'Financial Reporting', owner: 'John Davis', frequency: 'Daily', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-03-20' },
    { control_id: 'CTL-003', name: 'Bank Reconciliation', description: 'Monthly bank reconciliation for all accounts', category: 'Financial Reporting', owner: 'Sarah Chen', frequency: 'Monthly', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-03-01' },
    { control_id: 'CTL-004', name: 'Access Review - ERP', description: 'Quarterly review of ERP system access rights', category: 'IT', owner: 'Mike Johnson', frequency: 'Quarterly', status: 'In Progress', effectiveness: 'Partially Effective', last_tested: '2026-01-15' },
    { control_id: 'CTL-005', name: 'Segregation of Duties Check', description: 'Annual SoD matrix review across finance systems', category: 'Operations', owner: 'Lisa Wang', frequency: 'Annually', status: 'Pending', effectiveness: 'Not Tested', last_tested: null },
    { control_id: 'CTL-006', name: 'Inventory Count Verification', description: 'Physical inventory count reconciliation', category: 'Operations', owner: 'Tom Brown', frequency: 'Quarterly', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-03-30' },
    { control_id: 'CTL-007', name: 'Accounts Payable Three-Way Match', description: 'PO, receipt, and invoice matching for all purchases over $5K', category: 'Financial Reporting', owner: 'Amy Wilson', frequency: 'Daily', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-04-01' },
    { control_id: 'CTL-008', name: 'Financial Close Checklist', description: 'Month-end close procedures checklist completion', category: 'Financial Reporting', owner: 'Jane Smith', frequency: 'Monthly', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-03-31' },
    { control_id: 'CTL-009', name: 'IT Change Management', description: 'Review and approval of all production changes', category: 'IT', owner: 'David Lee', frequency: 'Weekly', status: 'In Progress', effectiveness: 'Partially Effective', last_tested: '2026-02-28' },
    { control_id: 'CTL-010', name: 'Payroll Processing Review', description: 'Review of payroll calculations and disbursements', category: 'Operations', owner: 'Karen Martinez', frequency: 'Monthly', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-03-25' },
    { control_id: 'CTL-011', name: 'Expense Report Approval', description: 'All expense reports over $500 require VP approval', category: 'Compliance', owner: 'Bob Taylor', frequency: 'Daily', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-04-02' },
    { control_id: 'CTL-012', name: 'Tax Provision Review', description: 'Quarterly tax provision calculation review', category: 'Financial Reporting', owner: 'Rachel Green', frequency: 'Quarterly', status: 'Pending', effectiveness: 'Not Tested', last_tested: null },
    { control_id: 'CTL-013', name: 'Fixed Asset Verification', description: 'Annual physical verification of fixed assets', category: 'Operations', owner: 'Tom Brown', frequency: 'Annually', status: 'Completed', effectiveness: 'Partially Effective', last_tested: '2025-12-15' },
    { control_id: 'CTL-014', name: 'Intercompany Reconciliation', description: 'Monthly reconciliation of intercompany balances', category: 'Financial Reporting', owner: 'Sarah Chen', frequency: 'Monthly', status: 'In Progress', effectiveness: 'Effective', last_tested: '2026-03-15' },
    { control_id: 'CTL-015', name: 'Data Backup Verification', description: 'Daily verification of critical system backups', category: 'IT', owner: 'David Lee', frequency: 'Daily', status: 'Completed', effectiveness: 'Effective', last_tested: '2026-04-05' },
  ]);

  // 2. Risk Assessments (15 items)
  await insertRows('risk_assessments', [
    { risk_id: 'RSK-001', title: 'Revenue Misstatement Risk', description: 'Risk of material misstatement in revenue recognition due to complex contracts', category: 'Financial', likelihood: 'Medium', impact: 'High', risk_score: 8, mitigation: 'Enhanced review procedures for complex contracts', owner: 'Jane Smith', status: 'Open' },
    { risk_id: 'RSK-002', title: 'Unauthorized Access to Financial Systems', description: 'Risk of unauthorized users gaining access to ERP financial modules', category: 'Technology', likelihood: 'Medium', impact: 'High', risk_score: 7, mitigation: 'Quarterly access reviews and MFA implementation', owner: 'Mike Johnson', status: 'In Progress' },
    { risk_id: 'RSK-003', title: 'Inventory Valuation Error', description: 'Risk of incorrect inventory valuation due to obsolescence', category: 'Financial', likelihood: 'High', impact: 'Medium', risk_score: 7, mitigation: 'Quarterly inventory write-down analysis', owner: 'Tom Brown', status: 'Open' },
    { risk_id: 'RSK-004', title: 'Regulatory Non-Compliance', description: 'Risk of non-compliance with new SEC reporting requirements', category: 'Compliance', likelihood: 'Low', impact: 'Critical', risk_score: 6, mitigation: 'Legal team monitoring and quarterly compliance training', owner: 'Lisa Wang', status: 'Mitigated' },
    { risk_id: 'RSK-005', title: 'Cyber Security Breach', description: 'Risk of data breach impacting financial data integrity', category: 'Technology', likelihood: 'Medium', impact: 'Critical', risk_score: 9, mitigation: 'Enhanced security monitoring and incident response plan', owner: 'David Lee', status: 'Open' },
    { risk_id: 'RSK-006', title: 'Vendor Fraud', description: 'Risk of fraudulent vendor payments through fictitious vendors', category: 'Operational', likelihood: 'Low', impact: 'High', risk_score: 5, mitigation: 'Vendor verification procedures and duplicate payment detection', owner: 'Amy Wilson', status: 'Mitigated' },
    { risk_id: 'RSK-007', title: 'Foreign Currency Translation Error', description: 'Risk of errors in multi-currency financial consolidation', category: 'Financial', likelihood: 'Medium', impact: 'Medium', risk_score: 6, mitigation: 'Automated FX rate feeds and reconciliation', owner: 'Sarah Chen', status: 'In Progress' },
    { risk_id: 'RSK-008', title: 'Key Personnel Dependency', description: 'Risk of knowledge loss from departure of critical finance staff', category: 'Operational', likelihood: 'High', impact: 'Medium', risk_score: 7, mitigation: 'Cross-training program and documentation initiative', owner: 'Karen Martinez', status: 'Open' },
    { risk_id: 'RSK-009', title: 'Lease Accounting Complexity', description: 'Risk of misapplication of ASC 842 lease accounting standard', category: 'Financial', likelihood: 'Medium', impact: 'Medium', risk_score: 5, mitigation: 'Specialized lease accounting software and training', owner: 'Rachel Green', status: 'Mitigated' },
    { risk_id: 'RSK-010', title: 'Related Party Transaction Disclosure', description: 'Risk of incomplete disclosure of related party transactions', category: 'Compliance', likelihood: 'Low', impact: 'High', risk_score: 4, mitigation: 'Annual related party questionnaires and monitoring', owner: 'Bob Taylor', status: 'Open' },
    { risk_id: 'RSK-011', title: 'Goodwill Impairment Assessment', description: 'Risk of incorrect goodwill impairment testing methodology', category: 'Financial', likelihood: 'Medium', impact: 'High', risk_score: 7, mitigation: 'External valuation specialist engagement', owner: 'Jane Smith', status: 'Open' },
    { risk_id: 'RSK-012', title: 'IT System Migration', description: 'Risk during planned ERP migration affecting data integrity', category: 'Technology', likelihood: 'High', impact: 'High', risk_score: 9, mitigation: 'Comprehensive migration plan with parallel running period', owner: 'David Lee', status: 'In Progress' },
    { risk_id: 'RSK-013', title: 'Tax Position Uncertainty', description: 'Risk of uncertain tax positions requiring additional reserves', category: 'Financial', likelihood: 'Medium', impact: 'Medium', risk_score: 5, mitigation: 'Quarterly tax position review with external advisors', owner: 'Rachel Green', status: 'Mitigated' },
    { risk_id: 'RSK-014', title: 'Third-Party Service Provider Risk', description: 'Risk of service provider failures affecting financial operations', category: 'Operational', likelihood: 'Low', impact: 'Medium', risk_score: 4, mitigation: 'SOC report reviews and vendor risk assessments', owner: 'Mike Johnson', status: 'Closed' },
    { risk_id: 'RSK-015', title: 'Payroll Processing Error', description: 'Risk of systematic payroll calculation or disbursement errors', category: 'Operational', likelihood: 'Low', impact: 'Medium', risk_score: 3, mitigation: 'Automated payroll controls and reconciliation', owner: 'Karen Martinez', status: 'Mitigated' },
  ]);

  // 3. Evidence (15 items)
  await insertRows('evidence', [
    { evidence_id: 'EVD-001', title: 'Q1 Bank Reconciliation Workpaper', description: 'Complete bank reconciliation for all accounts Q1 2026', control_ref: 'CTL-003', type: 'Document', source: 'Finance Department', collected_by: 'Sarah Chen', collected_date: '2026-03-31', status: 'Approved' },
    { evidence_id: 'EVD-002', title: 'ERP Access Rights Export', description: 'System-generated list of all active ERP users and roles', control_ref: 'CTL-004', type: 'System Extract', source: 'SAP', collected_by: 'Mike Johnson', collected_date: '2026-03-15', status: 'Approved' },
    { evidence_id: 'EVD-003', title: 'Revenue Recognition Memo', description: 'Q1 revenue recognition analysis for top 20 contracts', control_ref: 'CTL-001', type: 'Document', source: 'Revenue Accounting', collected_by: 'Jane Smith', collected_date: '2026-03-25', status: 'Approved' },
    { evidence_id: 'EVD-004', title: 'Journal Entry Approval Screenshots', description: 'Screenshots showing approval workflow for selected JEs', control_ref: 'CTL-002', type: 'Screenshot', source: 'ERP System', collected_by: 'John Davis', collected_date: '2026-03-20', status: 'Pending Review' },
    { evidence_id: 'EVD-005', title: 'Inventory Count Sheets', description: 'Physical inventory count documentation for Q1', control_ref: 'CTL-006', type: 'Document', source: 'Warehouse', collected_by: 'Tom Brown', collected_date: '2026-03-30', status: 'Approved' },
    { evidence_id: 'EVD-006', title: 'Payroll Reconciliation Report', description: 'Monthly payroll to GL reconciliation for March', control_ref: 'CTL-010', type: 'Report', source: 'HR/Payroll', collected_by: 'Karen Martinez', collected_date: '2026-03-28', status: 'Approved' },
    { evidence_id: 'EVD-007', title: 'Change Management Ticket Log', description: 'All production change tickets for Q1 with approvals', control_ref: 'CTL-009', type: 'System Extract', source: 'ServiceNow', collected_by: 'David Lee', collected_date: '2026-04-01', status: 'Pending Review' },
    { evidence_id: 'EVD-008', title: 'AP Three-Way Match Report', description: 'Sample of 25 purchase transactions with PO/receipt/invoice', control_ref: 'CTL-007', type: 'Report', source: 'AP Department', collected_by: 'Amy Wilson', collected_date: '2026-03-22', status: 'Approved' },
    { evidence_id: 'EVD-009', title: 'Financial Close Checklist - March', description: 'Completed month-end close checklist with sign-offs', control_ref: 'CTL-008', type: 'Document', source: 'Finance', collected_by: 'Jane Smith', collected_date: '2026-03-31', status: 'Approved' },
    { evidence_id: 'EVD-010', title: 'Backup Verification Logs', description: 'Daily backup verification logs for March 2026', control_ref: 'CTL-015', type: 'System Extract', source: 'IT Operations', collected_by: 'David Lee', collected_date: '2026-04-02', status: 'Approved' },
    { evidence_id: 'EVD-011', title: 'Expense Report Approval Email', description: 'Sample of 15 expense reports with VP approval evidence', control_ref: 'CTL-011', type: 'Email', source: 'Concur System', collected_by: 'Bob Taylor', collected_date: '2026-04-03', status: 'Pending Review' },
    { evidence_id: 'EVD-012', title: 'Fixed Asset Register Extract', description: 'Complete fixed asset listing with depreciation schedules', control_ref: 'CTL-013', type: 'System Extract', source: 'ERP System', collected_by: 'Tom Brown', collected_date: '2026-01-15', status: 'Approved' },
    { evidence_id: 'EVD-013', title: 'Intercompany Recon Workpaper', description: 'March intercompany elimination and reconciliation', control_ref: 'CTL-014', type: 'Document', source: 'Consolidation Team', collected_by: 'Sarah Chen', collected_date: '2026-03-31', status: 'Pending Review' },
    { evidence_id: 'EVD-014', title: 'SoD Matrix Review Documentation', description: 'Annual SoD conflict review analysis and resolution', control_ref: 'CTL-005', type: 'Document', source: 'Internal Audit', collected_by: 'Lisa Wang', collected_date: '2026-02-28', status: 'Rejected' },
    { evidence_id: 'EVD-015', title: 'Tax Provision Calculation Workpaper', description: 'Q4 2025 tax provision calculation and support', control_ref: 'CTL-012', type: 'Document', source: 'Tax Department', collected_by: 'Rachel Green', collected_date: '2026-01-31', status: 'Approved' },
  ]);

  // 4. Compliance Items (15 items)
  await insertRows('compliance_items', [
    { item_id: 'CMP-001', section: 'Section 302', requirement: 'CEO/CFO certification of quarterly financial reports', description: 'Officers must certify accuracy of financial statements and effectiveness of internal controls', status: 'Completed', assignee: 'CEO/CFO Office', due_date: '2026-04-15' },
    { item_id: 'CMP-002', section: 'Section 404', requirement: 'Annual assessment of internal control over financial reporting', description: 'Management must assess and report on ICFR effectiveness annually', status: 'In Progress', assignee: 'Internal Audit', due_date: '2026-06-30' },
    { item_id: 'CMP-003', section: 'Section 404', requirement: 'External auditor attestation on ICFR', description: 'External auditor must attest to management assessment of ICFR', status: 'Not Started', assignee: 'External Audit Firm', due_date: '2026-07-31' },
    { item_id: 'CMP-004', section: 'Section 302', requirement: 'Disclosure of material changes in internal controls', description: 'Any material changes in ICFR must be disclosed in quarterly reports', status: 'Completed', assignee: 'Legal Department', due_date: '2026-04-15' },
    { item_id: 'CMP-005', section: 'Section 906', requirement: 'Criminal certification of financial reports', description: 'CEO/CFO must certify reports comply with SEC requirements under penalty of law', status: 'Completed', assignee: 'CEO/CFO Office', due_date: '2026-04-15' },
    { item_id: 'CMP-006', section: 'Section 802', requirement: 'Document retention policy compliance', description: 'Maintain audit workpapers and relevant documents for minimum 7 years', status: 'In Progress', assignee: 'Records Management', due_date: '2026-12-31' },
    { item_id: 'CMP-007', section: 'Section 301', requirement: 'Audit committee independence requirements', description: 'All audit committee members must meet independence requirements', status: 'Completed', assignee: 'Corporate Governance', due_date: '2026-03-31' },
    { item_id: 'CMP-008', section: 'Section 404', requirement: 'Identify and document significant accounts', description: 'Document all significant accounts and relevant assertions', status: 'Completed', assignee: 'Internal Audit', due_date: '2026-03-15' },
    { item_id: 'CMP-009', section: 'Section 404', requirement: 'Entity-level controls assessment', description: 'Evaluate entity-level controls across COSO framework components', status: 'In Progress', assignee: 'Internal Audit', due_date: '2026-05-31' },
    { item_id: 'CMP-010', section: 'Section 404', requirement: 'IT General Controls testing', description: 'Test all ITGC controls supporting financial reporting systems', status: 'In Progress', assignee: 'IT Audit Team', due_date: '2026-05-15' },
    { item_id: 'CMP-011', section: 'Section 806', requirement: 'Whistleblower protection compliance', description: 'Ensure whistleblower hotline is operational and complaints are tracked', status: 'Completed', assignee: 'Ethics & Compliance', due_date: '2026-03-31' },
    { item_id: 'CMP-012', section: 'Section 404', requirement: 'Process-level controls documentation', description: 'Document and test process-level controls for all significant processes', status: 'In Progress', assignee: 'Internal Audit', due_date: '2026-06-15' },
    { item_id: 'CMP-013', section: 'Section 302', requirement: 'Disclosure controls assessment', description: 'Evaluate effectiveness of disclosure controls and procedures', status: 'Not Started', assignee: 'Legal Department', due_date: '2026-05-30' },
    { item_id: 'CMP-014', section: 'Section 404', requirement: 'Fraud risk assessment', description: 'Conduct annual fraud risk assessment per COSO and AS 2401', status: 'In Progress', assignee: 'Internal Audit', due_date: '2026-04-30' },
    { item_id: 'CMP-015', section: 'Section 1001', requirement: 'Corporate responsibility for financial reports', description: 'Ensure corporate responsibility provisions are met for all SEC filings', status: 'Completed', assignee: 'Legal Department', due_date: '2026-04-15' },
  ]);

  // 5. Deficiencies (15 items)
  await insertRows('deficiencies', [
    { deficiency_id: 'DEF-001', title: 'Inadequate Segregation of Duties in AP', description: 'Single user can create vendors and approve payments in ERP', control_ref: 'CTL-005', severity: 'High', classification: 'Significant Deficiency', identified_date: '2026-02-15', remediation_plan: 'Implement dual approval workflow', owner: 'Amy Wilson', status: 'In Progress' },
    { deficiency_id: 'DEF-002', title: 'Late Bank Reconciliation', description: 'Bank reconciliation for two accounts completed 15 days after month-end', control_ref: 'CTL-003', severity: 'Medium', classification: 'Control Deficiency', identified_date: '2026-03-01', remediation_plan: 'Hire additional staff and automate reconciliation', owner: 'Sarah Chen', status: 'Remediated' },
    { deficiency_id: 'DEF-003', title: 'Missing Revenue Recognition Documentation', description: 'Revenue recognition memos not prepared for 3 significant contracts', control_ref: 'CTL-001', severity: 'High', classification: 'Significant Deficiency', identified_date: '2026-01-20', remediation_plan: 'Mandatory memo template and review checklist', owner: 'Jane Smith', status: 'Open' },
    { deficiency_id: 'DEF-004', title: 'Excessive Admin Access to Production Database', description: '12 users have direct production database admin access without business justification', control_ref: 'CTL-004', severity: 'Critical', classification: 'Material Weakness', identified_date: '2026-02-01', remediation_plan: 'Immediate access review and removal of unnecessary privileges', owner: 'David Lee', status: 'In Progress' },
    { deficiency_id: 'DEF-005', title: 'Incomplete Journal Entry Review', description: 'Management review of journal entries below $10K threshold not performed consistently', control_ref: 'CTL-002', severity: 'Medium', classification: 'Control Deficiency', identified_date: '2026-03-10', remediation_plan: 'Lower review threshold and implement random sampling', owner: 'John Davis', status: 'Open' },
    { deficiency_id: 'DEF-006', title: 'IT Change Without Proper Approval', description: '5 production changes deployed without complete approval documentation', control_ref: 'CTL-009', severity: 'High', classification: 'Significant Deficiency', identified_date: '2026-02-20', remediation_plan: 'Enforce change management workflow in ticketing system', owner: 'David Lee', status: 'In Progress' },
    { deficiency_id: 'DEF-007', title: 'Inventory Count Discrepancy', description: 'Physical count vs. system variance exceeded 3% for raw materials category', control_ref: 'CTL-006', severity: 'Medium', classification: 'Control Deficiency', identified_date: '2026-03-30', remediation_plan: 'Implement cycle counting program', owner: 'Tom Brown', status: 'Open' },
    { deficiency_id: 'DEF-008', title: 'Fixed Asset Tagging Incomplete', description: '15% of fixed assets could not be physically located during verification', control_ref: 'CTL-013', severity: 'High', classification: 'Significant Deficiency', identified_date: '2025-12-20', remediation_plan: 'Complete asset tagging and implement barcode tracking', owner: 'Tom Brown', status: 'In Progress' },
    { deficiency_id: 'DEF-009', title: 'Payroll Ghost Employee Risk', description: 'Terminated employee payroll disbursement detected 2 months after termination', control_ref: 'CTL-010', severity: 'Critical', classification: 'Material Weakness', identified_date: '2026-03-05', remediation_plan: 'Real-time HR-Payroll integration and monthly terminated employee audit', owner: 'Karen Martinez', status: 'Open' },
    { deficiency_id: 'DEF-010', title: 'Expense Report Threshold Bypass', description: 'Expense reports split to avoid VP approval threshold', control_ref: 'CTL-011', severity: 'Medium', classification: 'Control Deficiency', identified_date: '2026-03-15', remediation_plan: 'System-enforced split detection and aggregate threshold checks', owner: 'Bob Taylor', status: 'Open' },
    { deficiency_id: 'DEF-011', title: 'Backup Restoration Testing Gap', description: 'No backup restoration test performed in last 6 months', control_ref: 'CTL-015', severity: 'High', classification: 'Significant Deficiency', identified_date: '2026-04-01', remediation_plan: 'Monthly backup restoration testing schedule', owner: 'David Lee', status: 'Open' },
    { deficiency_id: 'DEF-012', title: 'Intercompany Balance Mismatch', description: 'Unreconciled intercompany differences of $2.3M at quarter end', control_ref: 'CTL-014', severity: 'High', classification: 'Significant Deficiency', identified_date: '2026-03-31', remediation_plan: 'Implement automated intercompany matching system', owner: 'Sarah Chen', status: 'Open' },
    { deficiency_id: 'DEF-013', title: 'AP Three-Way Match Override', description: 'Excessive use of match exceptions and overrides in AP processing', control_ref: 'CTL-007', severity: 'Medium', classification: 'Control Deficiency', identified_date: '2026-02-28', remediation_plan: 'Reduce override authority and implement approval workflow for exceptions', owner: 'Amy Wilson', status: 'Remediated' },
    { deficiency_id: 'DEF-014', title: 'Tax Provision Calculation Error', description: 'Deferred tax liability calculation error of $1.5M identified in Q4 review', control_ref: 'CTL-012', severity: 'High', classification: 'Significant Deficiency', identified_date: '2026-01-31', remediation_plan: 'Enhanced tax provision review procedures and external specialist review', owner: 'Rachel Green', status: 'In Progress' },
    { deficiency_id: 'DEF-015', title: 'Financial Close Delay', description: 'Month-end close consistently exceeds target of 5 business days', control_ref: 'CTL-008', severity: 'Low', classification: 'Control Deficiency', identified_date: '2026-03-15', remediation_plan: 'Streamline close procedures and implement close management tool', owner: 'Jane Smith', status: 'Open' },
  ]);

  // 6. Walkthroughs (15 items)
  await insertRows('walkthroughs', [
    { walkthrough_id: 'WLK-001', process_name: 'Order-to-Cash Process', description: 'End-to-end walkthrough of the revenue cycle from order entry to cash collection', department: 'Finance', performed_by: 'Jane Smith', performed_date: '2026-02-10', participants: 'Sales Manager, AR Clerk, Revenue Accountant', findings: 'Manual steps in order approval create delay; recommend automation', status: 'Completed' },
    { walkthrough_id: 'WLK-002', process_name: 'Procure-to-Pay Process', description: 'Complete P2P cycle from requisition to payment', department: 'Procurement', performed_by: 'Amy Wilson', performed_date: '2026-02-15', participants: 'Procurement Manager, AP Supervisor, Budget Analyst', findings: 'PO creation and goods receipt in same department - SoD concern', status: 'Completed' },
    { walkthrough_id: 'WLK-003', process_name: 'Financial Reporting Close', description: 'Month-end close and financial statement preparation process', department: 'Accounting', performed_by: 'Sarah Chen', performed_date: '2026-02-20', participants: 'Controller, GL Accountant, Consolidation Analyst', findings: 'Multiple manual journal entries; consolidation done via spreadsheets', status: 'Completed' },
    { walkthrough_id: 'WLK-004', process_name: 'Payroll Processing', description: 'End-to-end payroll processing including time entry to disbursement', department: 'HR', performed_by: 'Karen Martinez', performed_date: '2026-03-01', participants: 'HR Director, Payroll Manager, Benefits Coordinator', findings: 'Time entry approvals not consistently documented', status: 'Completed' },
    { walkthrough_id: 'WLK-005', process_name: 'IT Access Provisioning', description: 'User access request, approval, and provisioning process for financial systems', department: 'IT', performed_by: 'Mike Johnson', performed_date: '2026-03-05', participants: 'IT Security Manager, Help Desk Lead, Business Application Owner', findings: 'Access request forms lack business justification field', status: 'Completed' },
    { walkthrough_id: 'WLK-006', process_name: 'Inventory Management', description: 'Inventory receipt, storage, valuation, and reporting process', department: 'Operations', performed_by: 'Tom Brown', performed_date: '2026-03-10', participants: 'Warehouse Manager, Cost Accountant, Supply Chain Analyst', findings: 'Goods receipt done without immediate system entry; 2-3 day lag', status: 'Completed' },
    { walkthrough_id: 'WLK-007', process_name: 'Treasury Management', description: 'Cash management, banking, and investment activities', department: 'Finance', performed_by: 'Sarah Chen', performed_date: '2026-03-12', participants: 'Treasurer, Cash Manager, Investment Analyst', findings: 'Wire transfers lack dual authorization for amounts over $50K', status: 'In Progress' },
    { walkthrough_id: 'WLK-008', process_name: 'Fixed Asset Lifecycle', description: 'Asset acquisition, capitalization, depreciation, and disposal', department: 'Accounting', performed_by: 'Tom Brown', performed_date: '2026-03-15', participants: 'Asset Manager, GL Accountant, Facilities Manager', findings: 'Disposal approvals not consistently obtained before asset removal', status: 'Completed' },
    { walkthrough_id: 'WLK-009', process_name: 'Tax Compliance Process', description: 'Tax provision, payment, and filing process', department: 'Finance', performed_by: 'Rachel Green', performed_date: '2026-03-18', participants: 'Tax Director, Tax Analyst, Legal Counsel', findings: 'Tax provision relies heavily on spreadsheets; lack of automation', status: 'Completed' },
    { walkthrough_id: 'WLK-010', process_name: 'IT Change Management', description: 'System change request, development, testing, and deployment process', department: 'IT', performed_by: 'David Lee', performed_date: '2026-03-20', participants: 'Development Lead, QA Manager, Release Manager', findings: 'Emergency changes bypass testing in some cases', status: 'Completed' },
    { walkthrough_id: 'WLK-011', process_name: 'Expense Reimbursement', description: 'Employee expense submission, approval, and reimbursement', department: 'Finance', performed_by: 'Bob Taylor', performed_date: '2026-03-22', participants: 'Travel Manager, AP Coordinator, Compliance Officer', findings: 'Receipt requirements not enforced for expenses under $25', status: 'Draft' },
    { walkthrough_id: 'WLK-012', process_name: 'Intercompany Transactions', description: 'Intercompany billing, reconciliation, and elimination process', department: 'Accounting', performed_by: 'Sarah Chen', performed_date: '2026-03-25', participants: 'Consolidation Manager, IC Accountants from 3 entities', findings: 'Different chart of accounts across entities complicates reconciliation', status: 'In Progress' },
    { walkthrough_id: 'WLK-013', process_name: 'Accounts Receivable Management', description: 'Credit approval, invoicing, collections, and bad debt process', department: 'Finance', performed_by: 'Jane Smith', performed_date: '2026-03-28', participants: 'Credit Manager, Collections Supervisor, Revenue Accountant', findings: 'Credit limits not reviewed annually for all customers', status: 'Completed' },
    { walkthrough_id: 'WLK-014', process_name: 'Data Backup and Recovery', description: 'Backup scheduling, execution, monitoring, and recovery testing', department: 'IT', performed_by: 'David Lee', performed_date: '2026-04-01', participants: 'Infrastructure Manager, DBA, Disaster Recovery Coordinator', findings: 'Recovery time objective testing not performed quarterly as planned', status: 'Draft' },
    { walkthrough_id: 'WLK-015', process_name: 'Lease Accounting Process', description: 'Lease identification, classification, measurement, and disclosure per ASC 842', department: 'Accounting', performed_by: 'Rachel Green', performed_date: '2026-04-03', participants: 'Lease Administrator, GL Accountant, Real Estate Manager', findings: 'Embedded leases in service contracts not consistently identified', status: 'In Progress' },
  ]);

  // 7. Management Reviews (15 items)
  await insertRows('management_reviews', [
    { review_id: 'MRV-001', title: 'Q1 Revenue Variance Analysis', description: 'Analysis of revenue variances vs budget and prior year for Q1', review_type: 'Variance Analysis', reviewer: 'CFO', review_date: '2026-04-10', period: 'Q1 2026', findings: 'Revenue 5% above budget driven by enterprise segment growth', conclusion: 'Satisfactory', status: 'Completed' },
    { review_id: 'MRV-002', title: 'March Bank Account Reconciliation Review', description: 'Management review of all bank reconciliations for March', review_type: 'Account Reconciliation', reviewer: 'Controller', review_date: '2026-04-05', period: 'March 2026', findings: 'All accounts reconciled within policy timeframes', conclusion: 'Satisfactory', status: 'Completed' },
    { review_id: 'MRV-003', title: 'Q1 Budget vs Actual Analysis', description: 'Comprehensive analysis of actual results vs approved budget', review_type: 'Budget vs Actual', reviewer: 'VP Finance', review_date: '2026-04-12', period: 'Q1 2026', findings: 'Operating expenses 8% over budget due to unplanned consulting spend', conclusion: 'Needs Improvement', status: 'Completed' },
    { review_id: 'MRV-004', title: 'March Journal Entry Review', description: 'Review of all manual and non-standard journal entries for March', review_type: 'Journal Entry Review', reviewer: 'Controller', review_date: '2026-04-03', period: 'March 2026', findings: '3 journal entries lacked adequate supporting documentation', conclusion: 'Needs Improvement', status: 'Completed' },
    { review_id: 'MRV-005', title: 'Q1 Financial Statement Disclosure Review', description: 'Review of quarterly financial statement disclosures for completeness', review_type: 'Disclosure Review', reviewer: 'CFO', review_date: '2026-04-15', period: 'Q1 2026', findings: null, conclusion: null, status: 'Scheduled' },
    { review_id: 'MRV-006', title: 'Inventory Reserve Estimate Review', description: 'Review of inventory obsolescence reserve methodology and calculations', review_type: 'Estimate Review', reviewer: 'Controller', review_date: '2026-03-28', period: 'Q1 2026', findings: 'Reserve methodology appropriate but slow-moving threshold needs update', conclusion: 'Satisfactory', status: 'Completed' },
    { review_id: 'MRV-007', title: 'Allowance for Doubtful Accounts Review', description: 'Review of bad debt reserve estimate and aging analysis', review_type: 'Estimate Review', reviewer: 'VP Finance', review_date: '2026-04-08', period: 'Q1 2026', findings: 'One customer representing 15% of AR aging over 90 days', conclusion: 'Needs Improvement', status: 'Completed' },
    { review_id: 'MRV-008', title: 'Q1 Intercompany Balance Review', description: 'Review of intercompany account balances and elimination entries', review_type: 'Account Reconciliation', reviewer: 'Controller', review_date: '2026-04-07', period: 'Q1 2026', findings: 'Elimination entries processed correctly; $2.3M difference under investigation', conclusion: 'Needs Improvement', status: 'Completed' },
    { review_id: 'MRV-009', title: 'March Operating Expense Review', description: 'Detailed review of operating expenses by department', review_type: 'Variance Analysis', reviewer: 'CFO', review_date: '2026-04-05', period: 'March 2026', findings: 'Marketing spend significantly over budget due to product launch', conclusion: 'Satisfactory', status: 'Completed' },
    { review_id: 'MRV-010', title: 'Q1 Tax Provision Review', description: 'Review of quarterly tax provision calculations', review_type: 'Estimate Review', reviewer: 'VP Finance', review_date: '2026-04-14', period: 'Q1 2026', findings: null, conclusion: null, status: 'Scheduled' },
    { review_id: 'MRV-011', title: 'Fixed Asset Roll-Forward Review', description: 'Review of fixed asset additions, disposals, and depreciation', review_type: 'Account Reconciliation', reviewer: 'Controller', review_date: '2026-04-06', period: 'Q1 2026', findings: 'Three disposals not properly removed from asset register', conclusion: 'Needs Improvement', status: 'Completed' },
    { review_id: 'MRV-012', title: 'Q1 Cash Flow Analysis', description: 'Analysis of cash flow statement components and significant movements', review_type: 'Variance Analysis', reviewer: 'Treasurer', review_date: '2026-04-09', period: 'Q1 2026', findings: 'Free cash flow declined 20% YoY due to CapEx investments', conclusion: 'Satisfactory', status: 'Completed' },
    { review_id: 'MRV-013', title: 'Lease Liability Estimate Review', description: 'Review of lease obligation calculations under ASC 842', review_type: 'Estimate Review', reviewer: 'Controller', review_date: '2026-04-11', period: 'Q1 2026', findings: 'Discount rate assumptions require update based on current market', conclusion: 'Needs Improvement', status: 'In Progress' },
    { review_id: 'MRV-014', title: 'Q1 Goodwill Impairment Indicator Assessment', description: 'Quarterly assessment of goodwill impairment indicators', review_type: 'Estimate Review', reviewer: 'CFO', review_date: '2026-04-13', period: 'Q1 2026', findings: null, conclusion: null, status: 'Scheduled' },
    { review_id: 'MRV-015', title: 'March Payroll Reconciliation Review', description: 'Review of payroll register to GL reconciliation', review_type: 'Account Reconciliation', reviewer: 'HR Director', review_date: '2026-04-04', period: 'March 2026', findings: 'Minor timing differences fully explained', conclusion: 'Satisfactory', status: 'Completed' },
  ]);

  // 8. ITGC Controls (15 items)
  await insertRows('itgc_controls', [
    { itgc_id: 'ITGC-001', name: 'Password Policy Enforcement', description: 'System-enforced password complexity, length, and rotation requirements', category: 'Access Security', system_name: 'SAP ERP', control_type: 'Preventive', owner: 'IT Security', test_result: 'Pass', test_date: '2026-03-15', status: 'Active' },
    { itgc_id: 'ITGC-002', name: 'Multi-Factor Authentication', description: 'MFA required for all remote access to financial systems', category: 'Access Security', system_name: 'All Financial Systems', control_type: 'Preventive', owner: 'IT Security', test_result: 'Pass', test_date: '2026-03-15', status: 'Active' },
    { itgc_id: 'ITGC-003', name: 'User Access Review - SAP', description: 'Quarterly review of user access rights in SAP', category: 'Access Security', system_name: 'SAP ERP', control_type: 'Detective', owner: 'Mike Johnson', test_result: 'Partially Effective', test_date: '2026-03-20', status: 'Active' },
    { itgc_id: 'ITGC-004', name: 'Change Management Approval', description: 'All production changes require documented testing and approval', category: 'Change Management', system_name: 'All Systems', control_type: 'Preventive', owner: 'David Lee', test_result: 'Fail', test_date: '2026-03-25', status: 'Active' },
    { itgc_id: 'ITGC-005', name: 'Source Code Version Control', description: 'All source code changes tracked in version control system', category: 'Program Development', system_name: 'Git/Azure DevOps', control_type: 'Preventive', owner: 'Development Lead', test_result: 'Pass', test_date: '2026-03-10', status: 'Active' },
    { itgc_id: 'ITGC-006', name: 'Database Backup - Daily', description: 'Daily automated backup of all production databases', category: 'Computer Operations', system_name: 'Production Databases', control_type: 'Preventive', owner: 'DBA Team', test_result: 'Pass', test_date: '2026-04-01', status: 'Active' },
    { itgc_id: 'ITGC-007', name: 'Backup Restoration Testing', description: 'Monthly restoration test of critical system backups', category: 'Computer Operations', system_name: 'All Critical Systems', control_type: 'Detective', owner: 'IT Operations', test_result: 'Fail', test_date: '2026-02-28', status: 'Active' },
    { itgc_id: 'ITGC-008', name: 'Privileged Account Management', description: 'Monitoring and control of privileged/admin accounts', category: 'Access Security', system_name: 'All Systems', control_type: 'Detective', owner: 'IT Security', test_result: 'Partially Effective', test_date: '2026-03-18', status: 'Active' },
    { itgc_id: 'ITGC-009', name: 'Network Firewall Configuration', description: 'Firewall rules reviewed and updated quarterly', category: 'Access Security', system_name: 'Network Infrastructure', control_type: 'Preventive', owner: 'Network Team', test_result: 'Pass', test_date: '2026-03-22', status: 'Active' },
    { itgc_id: 'ITGC-010', name: 'System Patch Management', description: 'Critical security patches applied within 30 days of release', category: 'Computer Operations', system_name: 'All Servers', control_type: 'Preventive', owner: 'IT Operations', test_result: 'Pass', test_date: '2026-04-05', status: 'Active' },
    { itgc_id: 'ITGC-011', name: 'Application Development Testing', description: 'Formal UAT sign-off required before production deployment', category: 'Program Development', system_name: 'Custom Applications', control_type: 'Preventive', owner: 'QA Manager', test_result: 'Pass', test_date: '2026-03-28', status: 'Active' },
    { itgc_id: 'ITGC-012', name: 'Antivirus/Malware Protection', description: 'Endpoint protection deployed and monitored on all workstations', category: 'Computer Operations', system_name: 'All Endpoints', control_type: 'Preventive', owner: 'IT Security', test_result: 'Pass', test_date: '2026-04-02', status: 'Active' },
    { itgc_id: 'ITGC-013', name: 'Audit Log Monitoring', description: 'Security event logs reviewed daily for suspicious activity', category: 'Access Security', system_name: 'SIEM Platform', control_type: 'Detective', owner: 'Security Operations', test_result: 'Pass', test_date: '2026-03-30', status: 'Active' },
    { itgc_id: 'ITGC-014', name: 'Separation of Environments', description: 'Development, test, and production environments physically separated', category: 'Program Development', system_name: 'All Systems', control_type: 'Preventive', owner: 'Infrastructure Team', test_result: 'Pass', test_date: '2026-03-12', status: 'Active' },
    { itgc_id: 'ITGC-015', name: 'Vendor Access Management', description: 'Third-party vendor access restricted and monitored', category: 'Access Security', system_name: 'VPN/Remote Access', control_type: 'Preventive', owner: 'IT Security', test_result: 'Partially Effective', test_date: '2026-03-20', status: 'Active' },
  ]);

  // 9. Financial Reviews (15 items)
  await insertRows('financial_reviews', [
    { review_id: 'FIN-001', account_name: 'Revenue - Product Sales', description: 'Product revenue from direct and channel sales', period: 'Q1 2026', balance: 45000000.00, prior_balance: 42500000.00, variance_pct: 5.88, reviewer: 'Jane Smith', status: 'Completed' },
    { review_id: 'FIN-002', account_name: 'Revenue - Services', description: 'Professional services and consulting revenue', period: 'Q1 2026', balance: 12500000.00, prior_balance: 11800000.00, variance_pct: 5.93, reviewer: 'Jane Smith', status: 'Completed' },
    { review_id: 'FIN-003', account_name: 'Cost of Goods Sold', description: 'Direct costs of products and services sold', period: 'Q1 2026', balance: 28000000.00, prior_balance: 25500000.00, variance_pct: 9.80, reviewer: 'Sarah Chen', status: 'In Progress' },
    { review_id: 'FIN-004', account_name: 'Accounts Receivable', description: 'Trade receivables net of allowance', period: 'Q1 2026', balance: 18500000.00, prior_balance: 15200000.00, variance_pct: 21.71, reviewer: 'Sarah Chen', status: 'Pending' },
    { review_id: 'FIN-005', account_name: 'Inventory', description: 'Raw materials, WIP, and finished goods', period: 'Q1 2026', balance: 8200000.00, prior_balance: 7500000.00, variance_pct: 9.33, reviewer: 'Tom Brown', status: 'Completed' },
    { review_id: 'FIN-006', account_name: 'Goodwill', description: 'Goodwill from business acquisitions', period: 'Q1 2026', balance: 35000000.00, prior_balance: 35000000.00, variance_pct: 0.00, reviewer: 'Controller', status: 'Completed' },
    { review_id: 'FIN-007', account_name: 'Accounts Payable', description: 'Trade payables to vendors', period: 'Q1 2026', balance: 12300000.00, prior_balance: 10800000.00, variance_pct: 13.89, reviewer: 'Amy Wilson', status: 'In Progress' },
    { review_id: 'FIN-008', account_name: 'Accrued Liabilities', description: 'Accrued expenses including compensation and benefits', period: 'Q1 2026', balance: 6800000.00, prior_balance: 5900000.00, variance_pct: 15.25, reviewer: 'Controller', status: 'Pending' },
    { review_id: 'FIN-009', account_name: 'Operating Expenses - R&D', description: 'Research and development expenses', period: 'Q1 2026', balance: 8500000.00, prior_balance: 7200000.00, variance_pct: 18.06, reviewer: 'VP Finance', status: 'Completed' },
    { review_id: 'FIN-010', account_name: 'Operating Expenses - S&M', description: 'Sales and marketing expenses', period: 'Q1 2026', balance: 9200000.00, prior_balance: 7800000.00, variance_pct: 17.95, reviewer: 'VP Finance', status: 'Requires Adjustment' },
    { review_id: 'FIN-011', account_name: 'Property Plant & Equipment', description: 'Net PP&E including depreciation', period: 'Q1 2026', balance: 22000000.00, prior_balance: 20500000.00, variance_pct: 7.32, reviewer: 'Tom Brown', status: 'Completed' },
    { review_id: 'FIN-012', account_name: 'Long-term Debt', description: 'Long-term borrowings and credit facilities', period: 'Q1 2026', balance: 30000000.00, prior_balance: 30000000.00, variance_pct: 0.00, reviewer: 'Treasurer', status: 'Completed' },
    { review_id: 'FIN-013', account_name: 'Income Tax Payable', description: 'Current income tax liability', period: 'Q1 2026', balance: 2800000.00, prior_balance: 2200000.00, variance_pct: 27.27, reviewer: 'Rachel Green', status: 'In Progress' },
    { review_id: 'FIN-014', account_name: 'Deferred Revenue', description: 'Unearned revenue from prepaid contracts', period: 'Q1 2026', balance: 5500000.00, prior_balance: 4800000.00, variance_pct: 14.58, reviewer: 'Jane Smith', status: 'Pending' },
    { review_id: 'FIN-015', account_name: 'Stockholders Equity', description: 'Total stockholders equity including retained earnings', period: 'Q1 2026', balance: 65000000.00, prior_balance: 60000000.00, variance_pct: 8.33, reviewer: 'CFO', status: 'Completed' },
  ]);

  // 10. SoD Reviews (15 items)
  await insertRows('sod_reviews', [
    { sod_id: 'SOD-001', user_name: 'James Wilson', role_1: 'Vendor Master Maintenance', role_2: 'Payment Processing', system_name: 'SAP ERP', conflict_type: 'Authorization', risk_level: 'High', mitigation: 'Compensating detective control via monthly audit review', status: 'Open' },
    { sod_id: 'SOD-002', user_name: 'Maria Garcia', role_1: 'Customer Master Maintenance', role_2: 'Credit Memo Approval', system_name: 'SAP ERP', conflict_type: 'Authorization', risk_level: 'High', mitigation: null, status: 'Open' },
    { sod_id: 'SOD-003', user_name: 'Robert Kim', role_1: 'Purchase Order Creation', role_2: 'Goods Receipt', system_name: 'SAP ERP', conflict_type: 'Custody', risk_level: 'Medium', mitigation: 'Manager reviews all receipts weekly', status: 'Mitigated' },
    { sod_id: 'SOD-004', user_name: 'Linda Chen', role_1: 'GL Journal Entry', role_2: 'GL Journal Approval', system_name: 'SAP ERP', conflict_type: 'Record-keeping', risk_level: 'Critical', mitigation: null, status: 'Open' },
    { sod_id: 'SOD-005', user_name: 'David Park', role_1: 'System Admin', role_2: 'Financial Reporting', system_name: 'SAP ERP', conflict_type: 'Authorization', risk_level: 'High', mitigation: 'Activity logging enabled and reviewed monthly', status: 'Mitigated' },
    { sod_id: 'SOD-006', user_name: 'Emma Thompson', role_1: 'Payroll Processing', role_2: 'HR Employee Maintenance', system_name: 'Workday', conflict_type: 'Record-keeping', risk_level: 'High', mitigation: null, status: 'Open' },
    { sod_id: 'SOD-007', user_name: 'Michael Brown', role_1: 'Bank Reconciliation', role_2: 'Cash Disbursement', system_name: 'SAP ERP', conflict_type: 'Reconciliation', risk_level: 'Medium', mitigation: 'Dual signatures required on all disbursements', status: 'Mitigated' },
    { sod_id: 'SOD-008', user_name: 'Sarah Adams', role_1: 'Inventory Adjustment', role_2: 'Inventory Valuation', system_name: 'SAP ERP', conflict_type: 'Custody', risk_level: 'Medium', mitigation: 'Physical count verification by separate team', status: 'Mitigated' },
    { sod_id: 'SOD-009', user_name: 'Chris Martinez', role_1: 'AP Invoice Entry', role_2: 'AP Payment Run', system_name: 'SAP ERP', conflict_type: 'Authorization', risk_level: 'High', mitigation: null, status: 'Open' },
    { sod_id: 'SOD-010', user_name: 'Nancy Lee', role_1: 'Fixed Asset Creation', role_2: 'Fixed Asset Disposal', system_name: 'SAP ERP', conflict_type: 'Custody', risk_level: 'Medium', mitigation: 'Annual physical verification by independent team', status: 'Accepted' },
    { sod_id: 'SOD-011', user_name: 'Kevin O\'Brien', role_1: 'Security Admin', role_2: 'User Provisioning', system_name: 'Active Directory', conflict_type: 'Authorization', risk_level: 'High', mitigation: 'Privileged access management tool monitoring', status: 'Mitigated' },
    { sod_id: 'SOD-012', user_name: 'Jennifer Wu', role_1: 'Revenue Recognition', role_2: 'Customer Invoicing', system_name: 'SAP ERP', conflict_type: 'Record-keeping', risk_level: 'Medium', mitigation: 'Monthly reconciliation between AR sub-ledger and GL', status: 'Mitigated' },
    { sod_id: 'SOD-013', user_name: 'Andrew Taylor', role_1: 'Database Admin', role_2: 'Application Developer', system_name: 'Production Database', conflict_type: 'Authorization', risk_level: 'Critical', mitigation: null, status: 'Open' },
    { sod_id: 'SOD-014', user_name: 'Patricia Johnson', role_1: 'Budget Entry', role_2: 'Budget Approval', system_name: 'Planning System', conflict_type: 'Authorization', risk_level: 'Low', mitigation: 'Final approval by department VP', status: 'Accepted' },
    { sod_id: 'SOD-015', user_name: 'Steven White', role_1: 'Wire Transfer Initiation', role_2: 'Wire Transfer Approval', system_name: 'Banking Portal', conflict_type: 'Authorization', risk_level: 'Critical', mitigation: null, status: 'Open' },
  ]);

  // 11. Access Reviews (15 items)
  await insertRows('access_reviews', [
    { review_id: 'ACC-001', user_name: 'James Wilson', system_name: 'SAP ERP', access_level: 'Read/Write', department: 'Finance', last_login: '2026-04-05', appropriate: 'Approved', reviewer: 'Mike Johnson', review_date: '2026-03-15' },
    { review_id: 'ACC-002', user_name: 'Maria Garcia', system_name: 'SAP ERP', access_level: 'Admin', department: 'IT', last_login: '2026-04-06', appropriate: 'Approved', reviewer: 'Mike Johnson', review_date: '2026-03-15' },
    { review_id: 'ACC-003', user_name: 'Former Employee - J. Smith', system_name: 'SAP ERP', access_level: 'Read/Write', department: 'Accounting', last_login: '2025-12-15', appropriate: 'Rejected', reviewer: 'Mike Johnson', review_date: '2026-03-15', notes: 'Employee terminated Dec 2025 - access not removed' },
    { review_id: 'ACC-004', user_name: 'Robert Kim', system_name: 'Workday HCM', access_level: 'Read/Write', department: 'HR', last_login: '2026-04-04', appropriate: 'Approved', reviewer: 'Karen Martinez', review_date: '2026-03-18' },
    { review_id: 'ACC-005', user_name: 'Linda Chen', system_name: 'SAP ERP', access_level: 'Super Admin', department: 'Finance', last_login: '2026-04-06', appropriate: 'Needs Modification', reviewer: 'Mike Johnson', review_date: '2026-03-15', notes: 'Super Admin access exceeds role requirements' },
    { review_id: 'ACC-006', user_name: 'David Lee', system_name: 'Production Database', access_level: 'Admin', department: 'IT', last_login: '2026-04-06', appropriate: 'Approved', reviewer: 'CTO', review_date: '2026-03-20' },
    { review_id: 'ACC-007', user_name: 'Service Account - BatchProcess', system_name: 'SAP ERP', access_level: 'Service Account', department: 'IT', last_login: '2026-04-06', appropriate: 'Pending Review', reviewer: null, review_date: null, notes: 'Service account with broad access; owner unclear' },
    { review_id: 'ACC-008', user_name: 'Emma Thompson', system_name: 'Workday HCM', access_level: 'Admin', department: 'HR', last_login: '2026-04-03', appropriate: 'Approved', reviewer: 'HR Director', review_date: '2026-03-18' },
    { review_id: 'ACC-009', user_name: 'Contractor - T. Anderson', system_name: 'SAP ERP', access_level: 'Read Only', department: 'External', last_login: '2026-03-01', appropriate: 'Rejected', reviewer: 'Mike Johnson', review_date: '2026-03-15', notes: 'Contract ended Feb 2026; access should be removed' },
    { review_id: 'ACC-010', user_name: 'Amy Wilson', system_name: 'Banking Portal', access_level: 'Read/Write', department: 'Finance', last_login: '2026-04-05', appropriate: 'Approved', reviewer: 'Treasurer', review_date: '2026-03-22' },
    { review_id: 'ACC-011', user_name: 'Tom Brown', system_name: 'Inventory Management', access_level: 'Admin', department: 'Operations', last_login: '2026-04-04', appropriate: 'Approved', reviewer: 'VP Operations', review_date: '2026-03-20' },
    { review_id: 'ACC-012', user_name: 'Rachel Green', system_name: 'Tax Software', access_level: 'Read/Write', department: 'Finance', last_login: '2026-04-02', appropriate: 'Approved', reviewer: 'Tax Director', review_date: '2026-03-25' },
    { review_id: 'ACC-013', user_name: 'Generic Account - Finance', system_name: 'SAP ERP', access_level: 'Read/Write', department: 'Finance', last_login: '2026-04-01', appropriate: 'Rejected', reviewer: 'Mike Johnson', review_date: '2026-03-15', notes: 'Shared/generic accounts prohibited by policy' },
    { review_id: 'ACC-014', user_name: 'Bob Taylor', system_name: 'Concur Expenses', access_level: 'Admin', department: 'Finance', last_login: '2026-04-06', appropriate: 'Approved', reviewer: 'Controller', review_date: '2026-03-22' },
    { review_id: 'ACC-015', user_name: 'New Hire - P. Davis', system_name: 'SAP ERP', access_level: 'Read Only', department: 'Accounting', last_login: null, appropriate: 'Pending Review', reviewer: null, review_date: null, notes: 'New hire started April 1; access provisioned but not yet reviewed' },
  ]);

  // 12. Change Requests (15 items)
  await insertRows('change_requests', [
    { change_id: 'CHG-001', title: 'SAP Revenue Module Patch', description: 'Apply critical patch for revenue recognition calculation', system_name: 'SAP ERP', change_type: 'Standard', requestor: 'Jane Smith', approver: 'David Lee', request_date: '2026-03-01', implementation_date: '2026-03-15', status: 'Implemented', risk_level: 'Medium' },
    { change_id: 'CHG-002', title: 'Firewall Rule Update', description: 'Update firewall rules for new cloud service integration', system_name: 'Network Infrastructure', change_type: 'Normal', requestor: 'Network Team', approver: 'IT Security', request_date: '2026-03-05', implementation_date: '2026-03-20', status: 'Implemented', risk_level: 'High' },
    { change_id: 'CHG-003', title: 'Emergency Database Recovery', description: 'Emergency restoration of corrupted transaction table', system_name: 'Production Database', change_type: 'Emergency', requestor: 'DBA Team', approver: 'CTO', request_date: '2026-03-10', implementation_date: '2026-03-10', status: 'Implemented', risk_level: 'High' },
    { change_id: 'CHG-004', title: 'Payroll System Upgrade', description: 'Major version upgrade of payroll processing system', system_name: 'Workday HCM', change_type: 'Major', requestor: 'Karen Martinez', approver: 'VP Finance', request_date: '2026-02-15', implementation_date: '2026-04-15', status: 'Approved', risk_level: 'High' },
    { change_id: 'CHG-005', title: 'GL Account Structure Change', description: 'Add new cost centers for reorganized business units', system_name: 'SAP ERP', change_type: 'Standard', requestor: 'Controller', approver: 'CFO', request_date: '2026-03-20', implementation_date: '2026-04-01', status: 'Implemented', risk_level: 'Medium' },
    { change_id: 'CHG-006', title: 'MFA Implementation Phase 2', description: 'Extend MFA to internal financial applications', system_name: 'Identity Management', change_type: 'Major', requestor: 'IT Security', approver: 'CTO', request_date: '2026-02-01', implementation_date: '2026-05-01', status: 'Approved', risk_level: 'Medium' },
    { change_id: 'CHG-007', title: 'Report Server Migration', description: 'Migrate financial reporting server to new hardware', system_name: 'Reporting Platform', change_type: 'Standard', requestor: 'IT Operations', approver: 'David Lee', request_date: '2026-03-25', implementation_date: null, status: 'Pending', risk_level: 'Medium' },
    { change_id: 'CHG-008', title: 'AP Workflow Automation', description: 'Implement automated three-way match in AP module', system_name: 'SAP ERP', change_type: 'Normal', requestor: 'Amy Wilson', approver: 'Controller', request_date: '2026-03-15', implementation_date: '2026-04-30', status: 'Approved', risk_level: 'Medium' },
    { change_id: 'CHG-009', title: 'Security Patch Bundle - March', description: 'Monthly security patches for all Windows servers', system_name: 'All Servers', change_type: 'Standard', requestor: 'IT Operations', approver: 'IT Security', request_date: '2026-03-28', implementation_date: '2026-04-05', status: 'Implemented', risk_level: 'Low' },
    { change_id: 'CHG-010', title: 'Backup Retention Policy Change', description: 'Extend backup retention from 30 to 90 days per audit requirement', system_name: 'Backup Infrastructure', change_type: 'Standard', requestor: 'Internal Audit', approver: 'IT Operations', request_date: '2026-04-01', implementation_date: null, status: 'Pending', risk_level: 'Low' },
    { change_id: 'CHG-011', title: 'ERP Performance Optimization', description: 'Database indexing and query optimization for month-end processing', system_name: 'SAP ERP', change_type: 'Standard', requestor: 'DBA Team', approver: 'David Lee', request_date: '2026-03-22', implementation_date: '2026-03-29', status: 'Implemented', risk_level: 'Low' },
    { change_id: 'CHG-012', title: 'New Tax Module Installation', description: 'Install automated tax calculation module in ERP', system_name: 'SAP ERP', change_type: 'Major', requestor: 'Rachel Green', approver: 'CFO', request_date: '2026-03-01', implementation_date: '2026-06-30', status: 'Approved', risk_level: 'High' },
    { change_id: 'CHG-013', title: 'VPN Configuration Update', description: 'Update VPN split tunneling configuration for compliance', system_name: 'VPN/Remote Access', change_type: 'Standard', requestor: 'IT Security', approver: 'Network Team', request_date: '2026-04-02', implementation_date: null, status: 'Pending', risk_level: 'Medium' },
    { change_id: 'CHG-014', title: 'Inventory Barcode System', description: 'Deploy barcode scanning for physical inventory tracking', system_name: 'Inventory Management', change_type: 'Major', requestor: 'Tom Brown', approver: 'VP Operations', request_date: '2026-03-15', implementation_date: '2026-05-31', status: 'Approved', risk_level: 'Medium' },
    { change_id: 'CHG-015', title: 'Emergency Hotfix - Login Issue', description: 'Fix authentication timeout affecting financial system users', system_name: 'Identity Management', change_type: 'Emergency', requestor: 'Help Desk', approver: 'IT Security', request_date: '2026-04-03', implementation_date: '2026-04-03', status: 'Implemented', risk_level: 'Low' },
  ]);

  // 13. Audit Reports (15 items)
  await insertRows('audit_reports', [
    { report_id: 'RPT-001', title: 'Q1 2026 SOX 404 Assessment Report', description: 'Quarterly assessment of internal control over financial reporting', audit_type: 'SOX 404', scope: 'All significant processes and ITGC', period: 'Q1 2026', lead_auditor: 'Lisa Wang', status: 'In Progress', findings_count: 8, opinion: null },
    { report_id: 'RPT-002', title: 'Revenue Cycle Audit Report', description: 'Detailed audit of the order-to-cash process', audit_type: 'Internal Audit', scope: 'Revenue recognition, billing, collections', period: 'FY 2025', lead_auditor: 'Jane Smith', status: 'Final', findings_count: 5, opinion: 'Qualified' },
    { report_id: 'RPT-003', title: 'IT General Controls Review', description: 'Annual ITGC testing and assessment report', audit_type: 'ITGC Review', scope: 'Access security, change management, operations, development', period: 'FY 2025', lead_auditor: 'Mike Johnson', status: 'Final', findings_count: 4, opinion: 'Qualified' },
    { report_id: 'RPT-004', title: 'Procurement Process Audit', description: 'End-to-end audit of procure-to-pay process', audit_type: 'Internal Audit', scope: 'Vendor management, PO process, AP, payments', period: 'H2 2025', lead_auditor: 'Amy Wilson', status: 'Issued', findings_count: 3, opinion: 'Unqualified' },
    { report_id: 'RPT-005', title: 'External Audit Report FY 2025', description: 'Independent auditor report on financial statements', audit_type: 'External Audit', scope: 'Full financial statement audit', period: 'FY 2025', lead_auditor: 'Big Four Partner', status: 'Issued', findings_count: 2, opinion: 'Unqualified' },
    { report_id: 'RPT-006', title: 'Payroll Audit Report', description: 'Audit of payroll processing and controls', audit_type: 'Internal Audit', scope: 'Payroll calculation, disbursement, tax compliance', period: 'Q4 2025', lead_auditor: 'Karen Martinez', status: 'Final', findings_count: 3, opinion: 'Qualified' },
    { report_id: 'RPT-007', title: 'Treasury Operations Review', description: 'Review of treasury management and cash controls', audit_type: 'Internal Audit', scope: 'Cash management, investments, banking', period: 'FY 2025', lead_auditor: 'Sarah Chen', status: 'Draft', findings_count: 2, opinion: null },
    { report_id: 'RPT-008', title: 'Inventory Management Audit', description: 'Audit of inventory valuation and physical controls', audit_type: 'Internal Audit', scope: 'Inventory counting, valuation, obsolescence', period: 'Q1 2026', lead_auditor: 'Tom Brown', status: 'In Progress', findings_count: 4, opinion: null },
    { report_id: 'RPT-009', title: 'Cybersecurity Assessment Report', description: 'Annual cybersecurity risk assessment and testing', audit_type: 'Special Review', scope: 'Network security, endpoint protection, incident response', period: 'FY 2025', lead_auditor: 'David Lee', status: 'Final', findings_count: 6, opinion: 'Qualified' },
    { report_id: 'RPT-010', title: 'Vendor Risk Assessment Report', description: 'Review of third-party vendor risk management', audit_type: 'Special Review', scope: 'Critical vendors, SOC reports, contract compliance', period: 'FY 2025', lead_auditor: 'Mike Johnson', status: 'Issued', findings_count: 3, opinion: 'Unqualified' },
    { report_id: 'RPT-011', title: 'Fixed Asset Audit Report', description: 'Physical verification and valuation of fixed assets', audit_type: 'Internal Audit', scope: 'Asset existence, valuation, depreciation', period: 'FY 2025', lead_auditor: 'Tom Brown', status: 'Final', findings_count: 4, opinion: 'Qualified' },
    { report_id: 'RPT-012', title: 'Access Control Review Report', description: 'Comprehensive user access review across financial systems', audit_type: 'ITGC Review', scope: 'User access, privileged accounts, service accounts', period: 'Q1 2026', lead_auditor: 'Mike Johnson', status: 'Review', findings_count: 5, opinion: null },
    { report_id: 'RPT-013', title: 'Compliance Program Effectiveness', description: 'Assessment of overall SOX compliance program', audit_type: 'SOX 404', scope: 'Compliance framework, training, monitoring', period: 'FY 2025', lead_auditor: 'Lisa Wang', status: 'Issued', findings_count: 3, opinion: 'Unqualified' },
    { report_id: 'RPT-014', title: 'Fraud Risk Assessment Report', description: 'Annual fraud risk assessment per COSO framework', audit_type: 'Special Review', scope: 'All business processes and entity-level fraud risks', period: 'FY 2026', lead_auditor: 'Bob Taylor', status: 'In Progress', findings_count: 0, opinion: null },
    { report_id: 'RPT-015', title: 'Lease Accounting Compliance', description: 'ASC 842 implementation review and compliance assessment', audit_type: 'Special Review', scope: 'Lease identification, measurement, disclosure', period: 'FY 2025', lead_auditor: 'Rachel Green', status: 'Final', findings_count: 2, opinion: 'Unqualified' },
  ]);

  // 14. Policies (15 items)
  await insertRows('policies', [
    { policy_id: 'POL-001', title: 'Information Security Policy', description: 'Comprehensive information security requirements for all employees', category: 'IT Security', version: '3.2', effective_date: '2025-01-15', review_date: '2026-01-15', owner: 'CISO', status: 'Active' },
    { policy_id: 'POL-002', title: 'Financial Reporting Policy', description: 'Standards and procedures for financial statement preparation', category: 'Financial Reporting', version: '2.1', effective_date: '2025-07-01', review_date: '2026-07-01', owner: 'CFO', status: 'Active' },
    { policy_id: 'POL-003', title: 'Code of Conduct', description: 'Employee ethical standards and conduct requirements', category: 'Compliance', version: '4.0', effective_date: '2025-03-01', review_date: '2026-03-01', owner: 'General Counsel', status: 'Under Review' },
    { policy_id: 'POL-004', title: 'Whistleblower Policy', description: 'Procedures for reporting suspected fraud or misconduct', category: 'Compliance', version: '2.0', effective_date: '2025-06-01', review_date: '2026-06-01', owner: 'Ethics Officer', status: 'Active' },
    { policy_id: 'POL-005', title: 'Data Retention Policy', description: 'Requirements for retention and disposal of business records', category: 'Data Privacy', version: '1.5', effective_date: '2025-09-01', review_date: '2026-09-01', owner: 'Legal Department', status: 'Active' },
    { policy_id: 'POL-006', title: 'Change Management Policy', description: 'Requirements for managing changes to IT systems and infrastructure', category: 'IT Security', version: '2.3', effective_date: '2025-04-01', review_date: '2026-04-01', owner: 'IT Director', status: 'Under Review' },
    { policy_id: 'POL-007', title: 'Access Control Policy', description: 'User access management and authentication requirements', category: 'IT Security', version: '3.0', effective_date: '2025-08-01', review_date: '2026-08-01', owner: 'CISO', status: 'Active' },
    { policy_id: 'POL-008', title: 'Expense Reimbursement Policy', description: 'Guidelines for employee expense reporting and reimbursement', category: 'Financial Reporting', version: '2.5', effective_date: '2025-01-01', review_date: '2026-01-01', owner: 'Controller', status: 'Active' },
    { policy_id: 'POL-009', title: 'Vendor Management Policy', description: 'Requirements for vendor selection, onboarding, and monitoring', category: 'Operations', version: '1.2', effective_date: '2025-05-01', review_date: '2026-05-01', owner: 'Procurement Director', status: 'Active' },
    { policy_id: 'POL-010', title: 'Anti-Fraud Policy', description: 'Framework for fraud prevention, detection, and response', category: 'Compliance', version: '2.0', effective_date: '2025-02-01', review_date: '2026-02-01', owner: 'Internal Audit Director', status: 'Active' },
    { policy_id: 'POL-011', title: 'Business Continuity Policy', description: 'Requirements for business continuity and disaster recovery planning', category: 'Risk Management', version: '1.8', effective_date: '2025-10-01', review_date: '2026-10-01', owner: 'CTO', status: 'Active' },
    { policy_id: 'POL-012', title: 'Insider Trading Policy', description: 'Restrictions on trading company securities by insiders', category: 'Compliance', version: '3.1', effective_date: '2025-01-01', review_date: '2026-01-01', owner: 'General Counsel', status: 'Active' },
    { policy_id: 'POL-013', title: 'Data Privacy Policy', description: 'Privacy requirements for personal and financial data handling', category: 'Data Privacy', version: '2.0', effective_date: '2025-11-01', review_date: '2026-11-01', owner: 'DPO', status: 'Active' },
    { policy_id: 'POL-014', title: 'Segregation of Duties Policy', description: 'Requirements for maintaining proper segregation of duties', category: 'Operations', version: '1.5', effective_date: '2025-07-01', review_date: '2026-07-01', owner: 'Controller', status: 'Active' },
    { policy_id: 'POL-015', title: 'Internal Audit Charter', description: 'Authority, responsibility, and scope of internal audit function', category: 'Compliance', version: '2.2', effective_date: '2025-03-01', review_date: '2026-03-01', owner: 'Audit Committee', status: 'Active' },
  ]);

  // 15. Remediations (15 items)
  await insertRows('remediations', [
    { remediation_id: 'REM-001', title: 'Implement Dual AP Approval Workflow', description: 'Configure ERP to require separate users for vendor creation and payment approval', deficiency_ref: 'DEF-001', action_plan: 'Phase 1: Configure workflow. Phase 2: Test. Phase 3: Go live.', owner: 'Amy Wilson', priority: 'High', due_date: '2026-05-15', status: 'In Progress' },
    { remediation_id: 'REM-002', title: 'Automate Bank Reconciliation', description: 'Implement automated bank feed and reconciliation matching', deficiency_ref: 'DEF-002', action_plan: 'Select tool, configure matching rules, parallel run, go live', owner: 'Sarah Chen', priority: 'Medium', due_date: '2026-06-30', status: 'In Progress' },
    { remediation_id: 'REM-003', title: 'Revenue Recognition Documentation Template', description: 'Create mandatory memo template for all contracts over $100K', deficiency_ref: 'DEF-003', action_plan: 'Design template, train staff, implement in workflow', owner: 'Jane Smith', priority: 'High', due_date: '2026-04-30', status: 'In Progress' },
    { remediation_id: 'REM-004', title: 'Production Database Access Cleanup', description: 'Remove unnecessary admin access and implement PAM solution', deficiency_ref: 'DEF-004', action_plan: 'Audit current access, remove unnecessary privileges, implement CyberArk', owner: 'David Lee', priority: 'Critical', due_date: '2026-04-15', status: 'In Progress' },
    { remediation_id: 'REM-005', title: 'Lower JE Review Threshold', description: 'Implement review for all journal entries and random sampling below threshold', deficiency_ref: 'DEF-005', action_plan: 'Configure lower threshold, implement sampling module', owner: 'John Davis', priority: 'Medium', due_date: '2026-05-31', status: 'Not Started' },
    { remediation_id: 'REM-006', title: 'Enforce Change Management Workflow', description: 'Configure ticketing system to block deployment without approvals', deficiency_ref: 'DEF-006', action_plan: 'Configure ServiceNow gates, test workflow, enforce policy', owner: 'David Lee', priority: 'High', due_date: '2026-04-30', status: 'In Progress' },
    { remediation_id: 'REM-007', title: 'Cycle Counting Program', description: 'Implement perpetual cycle counting program to replace annual count', deficiency_ref: 'DEF-007', action_plan: 'Design counting schedule, train warehouse staff, implement tracking', owner: 'Tom Brown', priority: 'Medium', due_date: '2026-07-31', status: 'Not Started' },
    { remediation_id: 'REM-008', title: 'Complete Fixed Asset Tagging', description: 'Tag all assets and implement barcode tracking system', deficiency_ref: 'DEF-008', action_plan: 'Physical verification, tag untagged assets, deploy barcode scanners', owner: 'Tom Brown', priority: 'High', due_date: '2026-06-30', status: 'In Progress' },
    { remediation_id: 'REM-009', title: 'HR-Payroll System Integration', description: 'Real-time termination sync between HR and payroll systems', deficiency_ref: 'DEF-009', action_plan: 'Design API integration, develop, test, deploy', owner: 'Karen Martinez', priority: 'Critical', due_date: '2026-05-15', status: 'In Progress' },
    { remediation_id: 'REM-010', title: 'Expense Report Split Detection', description: 'Implement system control to detect and flag split expense reports', deficiency_ref: 'DEF-010', action_plan: 'Configure Concur rules, test detection, enable enforcement', owner: 'Bob Taylor', priority: 'Medium', due_date: '2026-06-15', status: 'Not Started' },
    { remediation_id: 'REM-011', title: 'Monthly Backup Restoration Testing', description: 'Establish regular backup restoration testing schedule', deficiency_ref: 'DEF-011', action_plan: 'Create test plan, schedule monthly tests, document results', owner: 'David Lee', priority: 'High', due_date: '2026-05-01', status: 'Not Started' },
    { remediation_id: 'REM-012', title: 'Automated IC Matching System', description: 'Implement automated intercompany transaction matching and reconciliation', deficiency_ref: 'DEF-012', action_plan: 'Select solution, configure matching rules, migrate manual process', owner: 'Sarah Chen', priority: 'High', due_date: '2026-08-31', status: 'Not Started' },
    { remediation_id: 'REM-013', title: 'AP Match Exception Controls', description: 'Tighten controls around three-way match exceptions and overrides', deficiency_ref: 'DEF-013', action_plan: 'Reduce override authority, implement approval workflow, monthly reporting', owner: 'Amy Wilson', priority: 'Medium', due_date: '2026-05-31', status: 'Completed' },
    { remediation_id: 'REM-014', title: 'Enhanced Tax Provision Review', description: 'Implement additional review layers for tax provision calculations', deficiency_ref: 'DEF-014', action_plan: 'Engage external specialist, add reconciliation step, implement review checklist', owner: 'Rachel Green', priority: 'High', due_date: '2026-04-30', status: 'In Progress' },
    { remediation_id: 'REM-015', title: 'Close Management Tool Implementation', description: 'Deploy close management software to streamline month-end', deficiency_ref: 'DEF-015', action_plan: 'Evaluate tools, select vendor, configure workflows, train team', owner: 'Jane Smith', priority: 'Low', due_date: '2026-09-30', status: 'Not Started' },
  ]);

  // 16. Audit Plans (15 items)
  await insertRows('audit_plans', [
    { plan_id: 'PLN-001', title: 'FY 2026 Annual SOX 404 Audit', description: 'Comprehensive annual SOX 404 assessment of ICFR', audit_type: 'Annual SOX', start_date: '2026-01-15', end_date: '2026-07-31', lead_auditor: 'Lisa Wang', team_members: 'Jane Smith, Mike Johnson, Sarah Chen', status: 'Executing', budget: 250000.00 },
    { plan_id: 'PLN-002', title: 'Q2 2026 ITGC Testing', description: 'Quarterly ITGC testing cycle for all in-scope systems', audit_type: 'ITGC Audit', start_date: '2026-04-01', end_date: '2026-05-31', lead_auditor: 'Mike Johnson', team_members: 'David Lee, IT Audit Staff', status: 'Executing', budget: 45000.00 },
    { plan_id: 'PLN-003', title: 'Procurement Process Deep Dive', description: 'In-depth audit of procurement and AP processes', audit_type: 'Process Audit', start_date: '2026-05-01', end_date: '2026-06-30', lead_auditor: 'Amy Wilson', team_members: 'Audit Associate 1, Audit Associate 2', status: 'Planning', budget: 35000.00 },
    { plan_id: 'PLN-004', title: 'Q2 Quarterly SOX Review', description: 'Quarterly testing of key controls for Q2 certification', audit_type: 'Quarterly Review', start_date: '2026-07-01', end_date: '2026-08-15', lead_auditor: 'Lisa Wang', team_members: 'Full audit team', status: 'Planning', budget: 60000.00 },
    { plan_id: 'PLN-005', title: 'Revenue Cycle Controls Testing', description: 'Testing of revenue cycle controls per SOX requirements', audit_type: 'Process Audit', start_date: '2026-04-15', end_date: '2026-05-31', lead_auditor: 'Jane Smith', team_members: 'Revenue Audit Staff', status: 'Executing', budget: 40000.00 },
    { plan_id: 'PLN-006', title: 'Cybersecurity Risk Assessment', description: 'Annual comprehensive cybersecurity risk assessment', audit_type: 'Special Investigation', start_date: '2026-06-01', end_date: '2026-07-15', lead_auditor: 'David Lee', team_members: 'IT Security Team, External Consultant', status: 'Planning', budget: 75000.00 },
    { plan_id: 'PLN-007', title: 'Payroll Compliance Audit', description: 'Audit of payroll processing, tax compliance, and controls', audit_type: 'Process Audit', start_date: '2026-05-15', end_date: '2026-06-30', lead_auditor: 'Karen Martinez', team_members: 'HR Audit Staff', status: 'Planning', budget: 30000.00 },
    { plan_id: 'PLN-008', title: 'ERP Migration Readiness Assessment', description: 'Pre-migration assessment of controls and data integrity risks', audit_type: 'Special Investigation', start_date: '2026-03-01', end_date: '2026-04-30', lead_auditor: 'David Lee', team_members: 'Mike Johnson, External SAP Consultant', status: 'Executing', budget: 85000.00 },
    { plan_id: 'PLN-009', title: 'Entity-Level Controls Assessment', description: 'Annual assessment of entity-level controls per COSO framework', audit_type: 'Annual SOX', start_date: '2026-04-01', end_date: '2026-05-15', lead_auditor: 'Lisa Wang', team_members: 'Bob Taylor, Senior Auditor', status: 'Executing', budget: 25000.00 },
    { plan_id: 'PLN-010', title: 'Treasury and Cash Management Audit', description: 'Review of treasury operations and cash management controls', audit_type: 'Process Audit', start_date: '2026-06-15', end_date: '2026-07-31', lead_auditor: 'Sarah Chen', team_members: 'Treasury Audit Staff', status: 'Planning', budget: 30000.00 },
    { plan_id: 'PLN-011', title: 'Fraud Risk Assessment', description: 'Annual fraud risk assessment across all business processes', audit_type: 'Annual SOX', start_date: '2026-03-15', end_date: '2026-04-30', lead_auditor: 'Bob Taylor', team_members: 'Lisa Wang, Legal Representative', status: 'Executing', budget: 20000.00 },
    { plan_id: 'PLN-012', title: 'Vendor SOC Report Review', description: 'Review of SOC reports from critical third-party vendors', audit_type: 'ITGC Audit', start_date: '2026-04-15', end_date: '2026-05-15', lead_auditor: 'Mike Johnson', team_members: 'IT Audit Associate', status: 'Planning', budget: 15000.00 },
    { plan_id: 'PLN-013', title: 'Fixed Asset Physical Verification', description: 'Physical verification audit of all material fixed assets', audit_type: 'Process Audit', start_date: '2026-08-01', end_date: '2026-09-15', lead_auditor: 'Tom Brown', team_members: 'Asset Audit Team', status: 'Planning', budget: 20000.00 },
    { plan_id: 'PLN-014', title: 'Q3 Quarterly SOX Review', description: 'Quarterly testing of key controls for Q3 certification', audit_type: 'Quarterly Review', start_date: '2026-10-01', end_date: '2026-11-15', lead_auditor: 'Lisa Wang', team_members: 'Full audit team', status: 'Planning', budget: 60000.00 },
    { plan_id: 'PLN-015', title: 'Year-End Close Process Audit', description: 'Audit of year-end close procedures and financial statement prep', audit_type: 'Annual SOX', start_date: '2026-12-15', end_date: '2027-02-28', lead_auditor: 'Jane Smith', team_members: 'Full audit team, External auditors', status: 'Planning', budget: 100000.00 },
  ]);

  // 17. Materiality Assessments (15 items)
  await insertRows('materiality_assessments', [
    { assessment_id: 'MAT-001', title: 'FY 2026 Overall Materiality', description: 'Annual overall materiality determination for financial statement audit', benchmark: 'Total Revenue', benchmark_value: 230000000.00, materiality_threshold: 11500000.00, tolerable_misstatement: 8625000.00, period: 'FY 2026', assessor: 'Lisa Wang', status: 'Approved' },
    { assessment_id: 'MAT-002', title: 'Q1 2026 Interim Materiality', description: 'Quarterly interim materiality assessment', benchmark: 'Total Revenue', benchmark_value: 57500000.00, materiality_threshold: 2875000.00, tolerable_misstatement: 2156250.00, period: 'Q1 2026', assessor: 'Lisa Wang', status: 'Approved' },
    { assessment_id: 'MAT-003', title: 'Revenue Cycle Materiality', description: 'Process-specific materiality for revenue cycle testing', benchmark: 'Total Revenue', benchmark_value: 230000000.00, materiality_threshold: 5750000.00, tolerable_misstatement: 4312500.00, period: 'FY 2026', assessor: 'Jane Smith', status: 'Approved' },
    { assessment_id: 'MAT-004', title: 'Inventory Materiality', description: 'Account-specific materiality for inventory testing', benchmark: 'Total Assets', benchmark_value: 180000000.00, materiality_threshold: 3600000.00, tolerable_misstatement: 2700000.00, period: 'FY 2026', assessor: 'Tom Brown', status: 'Approved' },
    { assessment_id: 'MAT-005', title: 'Cash & Treasury Materiality', description: 'Materiality for cash and treasury account testing', benchmark: 'Total Assets', benchmark_value: 180000000.00, materiality_threshold: 3600000.00, tolerable_misstatement: 2700000.00, period: 'FY 2026', assessor: 'Sarah Chen', status: 'Approved' },
    { assessment_id: 'MAT-006', title: 'Payroll Materiality', description: 'Materiality for payroll and compensation testing', benchmark: 'Total Revenue', benchmark_value: 230000000.00, materiality_threshold: 4600000.00, tolerable_misstatement: 3450000.00, period: 'FY 2026', assessor: 'Karen Martinez', status: 'Approved' },
    { assessment_id: 'MAT-007', title: 'PP&E Materiality', description: 'Materiality for property, plant, and equipment testing', benchmark: 'Total Assets', benchmark_value: 180000000.00, materiality_threshold: 3600000.00, tolerable_misstatement: 2700000.00, period: 'FY 2026', assessor: 'Tom Brown', status: 'Approved' },
    { assessment_id: 'MAT-008', title: 'Tax Provision Materiality', description: 'Materiality for income tax provision and deferred tax testing', benchmark: 'Net Income', benchmark_value: 25000000.00, materiality_threshold: 1250000.00, tolerable_misstatement: 937500.00, period: 'FY 2026', assessor: 'Rachel Green', status: 'Draft' },
    { assessment_id: 'MAT-009', title: 'Goodwill & Intangibles Materiality', description: 'Materiality for goodwill impairment and intangible asset testing', benchmark: 'Total Assets', benchmark_value: 180000000.00, materiality_threshold: 5400000.00, tolerable_misstatement: 4050000.00, period: 'FY 2026', assessor: 'Controller', status: 'Approved' },
    { assessment_id: 'MAT-010', title: 'Debt & Equity Materiality', description: 'Materiality for long-term debt and equity testing', benchmark: 'Equity', benchmark_value: 65000000.00, materiality_threshold: 3250000.00, tolerable_misstatement: 2437500.00, period: 'FY 2026', assessor: 'Treasurer', status: 'Approved' },
    { assessment_id: 'MAT-011', title: 'Operating Expense Materiality', description: 'Materiality for operating expense testing by category', benchmark: 'Total Revenue', benchmark_value: 230000000.00, materiality_threshold: 4600000.00, tolerable_misstatement: 3450000.00, period: 'FY 2026', assessor: 'VP Finance', status: 'Approved' },
    { assessment_id: 'MAT-012', title: 'Lease Liability Materiality', description: 'Materiality for ASC 842 lease obligation testing', benchmark: 'Total Assets', benchmark_value: 180000000.00, materiality_threshold: 2700000.00, tolerable_misstatement: 2025000.00, period: 'FY 2026', assessor: 'Rachel Green', status: 'Draft' },
    { assessment_id: 'MAT-013', title: 'Intercompany Materiality', description: 'Materiality for intercompany elimination testing', benchmark: 'Total Revenue', benchmark_value: 230000000.00, materiality_threshold: 5750000.00, tolerable_misstatement: 4312500.00, period: 'FY 2026', assessor: 'Sarah Chen', status: 'Approved' },
    { assessment_id: 'MAT-014', title: 'Q2 2026 Interim Materiality', description: 'Q2 quarterly interim materiality assessment', benchmark: 'Total Revenue', benchmark_value: 60000000.00, materiality_threshold: 3000000.00, tolerable_misstatement: 2250000.00, period: 'Q2 2026', assessor: 'Lisa Wang', status: 'Draft' },
    { assessment_id: 'MAT-015', title: 'Disclosure Materiality', description: 'Qualitative materiality assessment for financial disclosures', benchmark: 'Gross Profit', benchmark_value: 29500000.00, materiality_threshold: 1475000.00, tolerable_misstatement: 1106250.00, period: 'FY 2026', assessor: 'CFO', status: 'Approved' },
  ]);

  // 18. Incidents (15 items)
  await insertRows('incidents', [
    { incident_id: 'INC-001', title: 'Phishing Attack on Finance Team', description: 'Targeted phishing emails sent to 5 finance team members', category: 'Security Breach', severity: 'High', reported_by: 'IT Security', reported_date: '2026-03-15', root_cause: 'Sophisticated spear phishing bypassed email filters', impact_assessment: 'One user clicked link but MFA prevented account compromise', status: 'Resolved' },
    { incident_id: 'INC-002', title: 'ERP System Outage', description: 'SAP ERP unplanned outage lasting 4 hours during business hours', category: 'System Outage', severity: 'High', reported_by: 'Help Desk', reported_date: '2026-03-20', root_cause: 'Database connection pool exhaustion due to batch job conflict', impact_assessment: 'Financial processing delayed; no data loss', status: 'Resolved' },
    { incident_id: 'INC-003', title: 'Unauthorized Vendor Payment', description: 'Payment of $45K to vendor without proper PO approval', category: 'Compliance Violation', severity: 'Medium', reported_by: 'AP Supervisor', reported_date: '2026-03-10', root_cause: 'AP clerk processed payment using manual override', impact_assessment: 'Payment was legitimate but violated three-way match policy', status: 'Closed' },
    { incident_id: 'INC-004', title: 'Data Export Without Authorization', description: 'Employee downloaded full customer list without approval', category: 'Unauthorized Access', severity: 'High', reported_by: 'DLP System', reported_date: '2026-04-01', root_cause: 'Overly permissive data export permissions in CRM', impact_assessment: 'Investigation ongoing; no evidence of data misuse', status: 'Investigating' },
    { incident_id: 'INC-005', title: 'Failed Backup Recovery Test', description: 'Critical financial database backup failed to restore during test', category: 'System Outage', severity: 'Critical', reported_by: 'IT Operations', reported_date: '2026-02-28', root_cause: 'Backup corruption due to storage hardware failure', impact_assessment: 'Secondary backup site intact; recovery possible but delayed', status: 'Resolved' },
    { incident_id: 'INC-006', title: 'Duplicate Vendor Payments', description: 'System processed duplicate payments totaling $120K to 3 vendors', category: 'Process Failure', severity: 'High', reported_by: 'AP Manager', reported_date: '2026-03-25', root_cause: 'ERP batch job ran twice due to scheduling error', impact_assessment: 'All duplicate payments recovered; control gap identified', status: 'Resolved' },
    { incident_id: 'INC-007', title: 'Suspected Time Card Fraud', description: 'Manager reported potential ghost employee time entries', category: 'Fraud', severity: 'High', reported_by: 'Department Manager', reported_date: '2026-03-05', root_cause: 'Investigation pending', impact_assessment: 'Potential overpayment of approximately $8K over 3 months', status: 'Investigating' },
    { incident_id: 'INC-008', title: 'SSL Certificate Expiration', description: 'Financial reporting portal SSL certificate expired causing outage', category: 'System Outage', severity: 'Medium', reported_by: 'Users', reported_date: '2026-03-18', root_cause: 'Certificate renewal notification was missed', impact_assessment: '2-hour portal outage; no security breach', status: 'Resolved' },
    { incident_id: 'INC-009', title: 'Ransomware Attempt Blocked', description: 'Ransomware detected and quarantined on employee workstation', category: 'Security Breach', severity: 'Critical', reported_by: 'Endpoint Protection', reported_date: '2026-04-02', root_cause: 'Infected USB drive connected to workstation', impact_assessment: 'Contained to single endpoint; no lateral movement detected', status: 'Resolved' },
    { incident_id: 'INC-010', title: 'Incorrect Financial Statement Filed', description: 'Preliminary financial data sent to board before final adjustments', category: 'Compliance Violation', severity: 'Medium', reported_by: 'Controller', reported_date: '2026-04-05', root_cause: 'Draft report mistakenly marked as final in document management', impact_assessment: 'Corrected version sent immediately; no external disclosure impact', status: 'Closed' },
    { incident_id: 'INC-011', title: 'Vendor Portal Data Exposure', description: 'Vendor self-service portal exposed other vendors payment history', category: 'Data Loss', severity: 'High', reported_by: 'Vendor Report', reported_date: '2026-03-22', root_cause: 'SQL injection vulnerability in vendor portal search', impact_assessment: '15 vendors potentially affected; payment amounts visible', status: 'Resolved' },
    { incident_id: 'INC-012', title: 'Physical Security - Tailgating', description: 'Unauthorized person gained access to finance floor via tailgating', category: 'Security Breach', severity: 'Low', reported_by: 'Security Guard', reported_date: '2026-04-03', root_cause: 'Employee held door open for person without badge', impact_assessment: 'Person was a visitor who went to wrong floor; no data exposure', status: 'Closed' },
    { incident_id: 'INC-013', title: 'Cloud Storage Misconfiguration', description: 'Financial documents folder in cloud storage had public sharing enabled', category: 'Data Loss', severity: 'Critical', reported_by: 'Security Audit', reported_date: '2026-03-28', root_cause: 'Employee changed sharing settings to collaborate with external auditor', impact_assessment: 'Sensitive financial planning documents potentially exposed for 5 days', status: 'Investigating' },
    { incident_id: 'INC-014', title: 'Month-End Processing Error', description: 'Automated journal entry posting duplicated accrual entries', category: 'Process Failure', severity: 'Medium', reported_by: 'GL Accountant', reported_date: '2026-03-31', root_cause: 'Batch job scheduling overlap with manual posting', impact_assessment: 'Overstated accrued liabilities by $350K; reversed next day', status: 'Resolved' },
    { incident_id: 'INC-015', title: 'Third-Party API Key Exposure', description: 'API key for financial data service found in public code repository', category: 'Security Breach', severity: 'High', reported_by: 'GitHub Scanner', reported_date: '2026-04-04', root_cause: 'Developer accidentally committed .env file to public repo', impact_assessment: 'Key rotated within 1 hour; no unauthorized API calls detected', status: 'Resolved' },
  ]);

  console.log('Seed data inserted successfully!');
  await pool.end();
}

seed().catch(err => {
  console.error('Seed error:', err);
  process.exit(1);
});
